/**
 * LINGUAQUEST - VOCABULARY BANK LEVEL 1 (300 WORDS)
 * Kategori: Sangat Familiar (Daily Life, Home, School, Basic Actions)
 */

window.VOCAB_MASTER = window.VOCAB_MASTER || {};

window.VOCAB_MASTER.LV1 = [
    // --- ACTIONS / VERBS (90 Kata) ---
    { word: "eat", meaning: "makan", type: "verb", phonetic: "/iːt/" },
    { word: "drink", meaning: "minum", type: "verb", phonetic: "/drɪŋk/" },
    { word: "sleep", meaning: "tidur", type: "verb", phonetic: "/sliːp/" },
    { word: "go", meaning: "pergi", type: "verb", phonetic: "/ɡoʊ/" },
    { word: "come", meaning: "datang", type: "verb", phonetic: "/kʌm/" },
    { word: "see", meaning: "melihat", type: "verb", phonetic: "/siː/" },
    { word: "look", meaning: "melihat/memandang", type: "verb", phonetic: "/lʊk/" },
    { word: "sit", meaning: "duduk", type: "verb", phonetic: "/sɪt/" },
    { word: "stand", meaning: "berdiri", type: "verb", phonetic: "/stænd/" },
    { word: "run", meaning: "lari", type: "verb", phonetic: "/rʌn/" },
    { word: "walk", meaning: "jalan", type: "verb", phonetic: "/wɔːk/" },
    { word: "read", meaning: "membaca", type: "verb", phonetic: "/riːd/" },
    { word: "write", meaning: "menulis", type: "verb", phonetic: "/raɪt/" },
    { word: "study", meaning: "belajar", type: "verb", phonetic: "/ˈstʌd.i/" },
    { word: "learn", meaning: "belajar/mempelajari", type: "verb", phonetic: "/lɜːrn/" },
    { word: "play", meaning: "bermain", type: "verb", phonetic: "/pleɪ/" },
    { word: "work", meaning: "bekerja", type: "verb", phonetic: "/wɜːrk/" },
    { word: "help", meaning: "menolong", type: "verb", phonetic: "/help/" },
    { word: "open", meaning: "membuka", type: "verb", phonetic: "/ˈoʊ.pən/" },
    { word: "close", meaning: "menutup", type: "verb", phonetic: "/kloʊz/" },
    { word: "take", meaning: "mengambil", type: "verb", phonetic: "/teɪk/" },
    { word: "give", meaning: "memberi", type: "verb", phonetic: "/ɡɪv/" },
    { word: "bring", meaning: "membawa", type: "verb", phonetic: "/brɪŋ/" },
    { word: "buy", meaning: "membeli", type: "verb", phonetic: "/baɪ/" },
    { word: "cook", meaning: "memasak", type: "verb", phonetic: "/kʊk/" },
    { word: "clean", meaning: "membersihkan", type: "verb", phonetic: "/kliːn/" },
    { word: "wash", meaning: "mencuci", type: "verb", phonetic: "/wɒʃ/" },
    { word: "listen", meaning: "mendengar", type: "verb", phonetic: "/ˈlɪs.ən/" },
    { word: "speak", meaning: "berbicara", type: "verb", phonetic: "/spiːk/" },
    { word: "talk", meaning: "mengobrol", type: "verb", phonetic: "/tɔːk/" },
    { word: "jump", meaning: "lompat", type: "verb", phonetic: "/dʒʌmp/" },
    { word: "swim", meaning: "berenang", type: "verb", phonetic: "/swɪm/" },
    { word: "smile", meaning: "tersenyum", type: "verb", phonetic: "/smaɪl/" },
    { word: "laugh", meaning: "tertawa", type: "verb", phonetic: "/læf/" },
    { word: "cry", meaning: "menangis", type: "verb", phonetic: "/kraɪ/" },
    { word: "know", meaning: "tahu", type: "verb", phonetic: "/noʊ/" },
    { word: "think", meaning: "berpikir", type: "verb", phonetic: "/θɪŋk/" },
    { word: "call", meaning: "memanggil/menelepon", type: "verb", phonetic: "/kɔːl/" },
    { word: "wait", meaning: "tunggu", type: "verb", phonetic: "/weɪt/" },
    { word: "stop", meaning: "berhenti", type: "verb", phonetic: "/stɒp/" },
    { word: "want", meaning: "ingin", type: "verb", phonetic: "/wɒnt/" },
    { word: "need", meaning: "butuh", type: "verb", phonetic: "/niːd/" },
    { word: "like", meaning: "suka", type: "verb", phonetic: "/laɪk/" },
    { word: "love", meaning: "cinta/sangat suka", type: "verb", phonetic: "/lʌv/" },
    { word: "hate", meaning: "benci", type: "verb", phonetic: "/heɪt/" },
    { word: "feel", meaning: "merasa", type: "verb", phonetic: "/fiːl/" },
    { word: "use", meaning: "menggunakan", type: "verb", phonetic: "/juːz/" },
    { word: "make", meaning: "membuat", type: "verb", phonetic: "/meɪk/" },
    { word: "do", meaning: "melakukan", type: "verb", phonetic: "/duː/" },
    { word: "get", meaning: "mendapatkan", type: "verb", phonetic: "/ɡet/" },
    { word: "hear", meaning: "mendengar", type: "verb", phonetic: "/hɪər/" },
    { word: "wear", meaning: "memakai", type: "verb", phonetic: "/wer/" },
    { word: "drive", meaning: "menyetir", type: "verb", phonetic: "/draɪv/" },
    { word: "ride", meaning: "mengendarai", type: "verb", phonetic: "/raɪd/" },
    { word: "put", meaning: "meletakkan", type: "verb", phonetic: "/pʊt/" },
    { word: "show", meaning: "menunjukkan", type: "verb", phonetic: "/ʃoʊ/" },
    { word: "tell", meaning: "memberitahu", type: "verb", phonetic: "/tel/" },
    { word: "ask", meaning: "tanya", type: "verb", phonetic: "/æsk/" },
    { word: "answer", meaning: "jawab", type: "verb", phonetic: "/ˈæn.sər/" },
    { word: "try", meaning: "mencoba", type: "verb", phonetic: "/traɪ/" },
    { word: "begin", meaning: "mulai", type: "verb", phonetic: "/bɪˈɡɪn/" },
    { word: "finish", meaning: "selesai", type: "verb", phonetic: "/ˈfɪn.ɪʃ/" },
    { word: "keep", meaning: "menjaga", type: "verb", phonetic: "/kiːp/" },
    { word: "hold", meaning: "memegang", type: "verb", phonetic: "/hoʊld/" },
    { word: "cut", meaning: "memotong", type: "verb", phonetic: "/kʌt/" },
    { id: "v66", word: "fall", meaning: "jatuh", type: "verb", phonetic: "/fɔːl/" },
    { id: "v67", word: "sing", meaning: "menyanyi", type: "verb", phonetic: "/sɪŋ/" },
    { id: "v68", word: "dance", meaning: "menari", type: "verb", phonetic: "/dæns/" },
    { id: "v69", word: "watch", meaning: "menonton", type: "verb", phonetic: "/wɒtʃ/" },
    { id: "v70", word: "draw", meaning: "menggambar", type: "verb", phonetic: "/drɔː/" },
    { id: "v71", word: "dream", meaning: "bermimpi", type: "verb", phonetic: "/driːm/" },
    { id: "v72", word: "hope", meaning: "berharap", type: "verb", phonetic: "/hoʊp/" },
    { id: "v73", word: "brush", meaning: "menyikat", type: "verb", phonetic: "/brʌʃ/" },
    { id: "v74", word: "comb", meaning: "menyisir", type: "verb", phonetic: "/koʊm/" },
    { id: "v75", word: "carry", meaning: "membawa", type: "verb", phonetic: "/ˈkær.i/" },
    { id: "v76", word: "push", meaning: "mendorong", type: "verb", phonetic: "/pʊʃ/" },
    { id: "v77", word: "pull", meaning: "menarik", type: "verb", phonetic: "/pʊl/" },
    { id: "v78", word: "kick", meaning: "menendang", type: "verb", phonetic: "/kɪk/" },
    { id: "v79", word: "hit", meaning: "memukul", type: "verb", phonetic: "/hɪt/" },
    { id: "v80", word: "catch", meaning: "menangkap", type: "verb", phonetic: "/kætʃ/" },
    { id: "v81", word: "throw", meaning: "melempar", type: "verb", phonetic: "/θroʊ/" },
    { id: "v82", word: "climb", meaning: "memanjat", type: "verb", phonetic: "/klaɪm/" },
    { id: "v83", word: "fly", meaning: "terbang", type: "verb", phonetic: "/flaɪ/" },
    { id: "v84", word: "travel", meaning: "bepergian", type: "verb", phonetic: "/ˈtræv.əl/" },
    { id: "v85", word: "stay", meaning: "tinggal/diam", type: "verb", phonetic: "/steɪ/" },
    { id: "v86", word: "visit", meaning: "mengunjungi", type: "verb", phonetic: "/ˈvɪz.ɪt/" },
    { id: "v87", word: "celebrate", meaning: "merayakan", type: "verb", phonetic: "/ˈsel.ə.breɪt/" },
    { id: "v88", word: "borrow", meaning: "pinjam", type: "verb", phonetic: "/ˈbɒr.əʊ/" },
    { id: "v89", word: "lend", meaning: "meminjamkan", type: "verb", phonetic: "/lend/" },
    { id: "v90", word: "save", meaning: "menyimpan", type: "verb", phonetic: "/seɪv/" },

    // --- THINGS / NOUNS (130 Kata) ---
    { word: "apple", meaning: "apel", type: "noun", phonetic: "/ˈæp.əl/" },
    { word: "book", meaning: "buku", type: "noun", phonetic: "/bʊk/" },
    { word: "water", meaning: "air", type: "noun", phonetic: "/ˈwɔː.tər/" },
    { word: "milk", meaning: "susu", type: "noun", phonetic: "/mɪlk/" },
    { word: "coffee", meaning: "kopi", type: "noun", phonetic: "/ˈkɒf.i/" },
    { word: "tea", meaning: "teh", type: "noun", phonetic: "/tiː/" },
    { word: "bread", meaning: "roti", type: "noun", phonetic: "/bred/" },
    { word: "rice", meaning: "nasi", type: "noun", phonetic: "/raɪs/" },
    { word: "egg", meaning: "telur", type: "noun", phonetic: "/eɡ/" },
    { word: "fruit", meaning: "buah", type: "noun", phonetic: "/fruːt/" },
    { word: "meat", meaning: "daging", type: "noun", phonetic: "/miːt/" },
    { word: "fish", meaning: "ikan", type: "noun", phonetic: "/fɪʃ/" },
    { word: "sugar", meaning: "gula", type: "noun", phonetic: "/ˈʃʊɡ.ər/" },
    { word: "salt", meaning: "garam", type: "noun", phonetic: "/sɒlt/" },
    { word: "school", meaning: "sekolah", type: "noun", phonetic: "/skuːl/" },
    { word: "class", meaning: "kelas", type: "noun", phonetic: "/klæs/" },
    { word: "teacher", meaning: "guru", type: "noun", phonetic: "/ˈtiː.tʃər/" },
    { word: "student", meaning: "murid", type: "noun", phonetic: "/ˈstjuː.dənt/" },
    { word: "pen", meaning: "pena", type: "noun", phonetic: "/pen/" },
    { word: "pencil", meaning: "pensil", type: "noun", phonetic: "/ˈpen.səl/" },
    { word: "paper", meaning: "kertas", type: "noun", phonetic: "/ˈpeɪ.pər/" },
    { word: "bag", meaning: "tas", type: "noun", phonetic: "/bæɡ/" },
    { word: "desk", meaning: "meja tulis", type: "noun", phonetic: "/desk/" },
    { word: "chair", meaning: "kursi", type: "noun", phonetic: "/tʃer/" },
    { word: "home", meaning: "rumah", type: "noun", phonetic: "/hoʊm/" },
    { word: "house", meaning: "rumah (bangunan)", type: "noun", phonetic: "/haʊs/" },
    { word: "room", meaning: "kamar", type: "noun", phonetic: "/ruːm/" },
    { word: "door", meaning: "pintu", type: "noun", phonetic: "/dɔːr/" },
    { word: "window", meaning: "jendela", type: "noun", phonetic: "/ˈwɪn.doʊ/" },
    { word: "floor", meaning: "lantai", type: "noun", phonetic: "/flɔːr/" },
    { word: "wall", meaning: "dinding", type: "noun", phonetic: "/wɔːl/" },
    { word: "garden", meaning: "kebun", type: "noun", phonetic: "/ˈɡɑːr.dən/" },
    { word: "kitchen", meaning: "dapur", type: "noun", phonetic: "/ˈkɪtʃ.ən/" },
    { word: "bed", meaning: "tempat tidur", type: "noun", phonetic: "/bed/" },
    { word: "bathroom", meaning: "kamar mandi", type: "noun", phonetic: "/ˈbɑːθ.ruːm/" },
    { word: "soap", meaning: "sabun", type: "noun", phonetic: "/soʊp/" },
    { word: "towel", meaning: "handuk", type: "noun", phonetic: "/ˈtaʊ.əl/" },
    { word: "clothes", meaning: "pakaian", type: "noun", phonetic: "/kloʊðz/" },
    { word: "shirt", meaning: "kemeja", type: "noun", phonetic: "/ʃɜːrt/" },
    { word: "shoes", meaning: "sepatu", type: "noun", phonetic: "/ʃuːz/" },
    { word: "hat", meaning: "topi", type: "noun", phonetic: "/hæt/" },
    { word: "father", meaning: "ayah", type: "noun", phonetic: "/ˈfɑː.ðər/" },
    { word: "mother", meaning: "ibu", type: "noun", phonetic: "/ˈmʌð.ər/" },
    { word: "brother", meaning: "saudara laki-laki", type: "noun", phonetic: "/ˈbrʌð.ər/" },
    { word: "sister", meaning: "saudara perempuan", type: "noun", phonetic: "/ˈsɪs.tər/" },
    { word: "baby", meaning: "bayi", type: "noun", phonetic: "/ˈbeɪ.bi/" },
    { word: "friend", meaning: "teman", type: "noun", phonetic: "/frend/" },
    { word: "family", meaning: "keluarga", type: "noun", phonetic: "/ˈfæm.əl.i/" },
    { word: "man", meaning: "laki-laki", type: "noun", phonetic: "/mæn/" },
    { word: "woman", meaning: "perempuan", type: "noun", phonetic: "/ˈwʊm.ən/" },
    { word: "boy", meaning: "anak laki-laki", type: "noun", phonetic: "/bɔɪ/" },
    { word: "girl", meaning: "anak perempuan", type: "noun", phonetic: "/ɡɜːrl/" },
    { word: "name", meaning: "nama", type: "noun", phonetic: "/neɪm/" },
    { word: "body", meaning: "tubuh", type: "noun", phonetic: "/ˈbɒd.i/" },
    { word: "head", meaning: "kepala", type: "noun", phonetic: "/hed/" },
    { word: "hand", meaning: "tangan", type: "noun", phonetic: "/hænd/" },
    { word: "foot", meaning: "kaki", type: "noun", phonetic: "/fʊt/" },
    { word: "eye", meaning: "mata", type: "noun", phonetic: "/aɪ/" },
    { word: "nose", meaning: "hidung", type: "noun", phonetic: "/noʊz/" },
    { word: "mouth", meaning: "mulut", type: "noun", phonetic: "/maʊθ/" },
    { word: "ear", meaning: "telinga", type: "noun", phonetic: "/ɪər/" },
    { word: "hair", meaning: "rambut", type: "noun", phonetic: "/her/" },
    { word: "face", meaning: "wajah", type: "noun", phonetic: "/feɪs/" },
    { word: "money", meaning: "uang", type: "noun", phonetic: "/ˈmʌn.i/" },
    { word: "time", meaning: "waktu", type: "noun", phonetic: "/taɪm/" },
    { word: "day", meaning: "hari", type: "noun", phonetic: "/deɪ/" },
    { word: "night", meaning: "malam", type: "noun", phonetic: "/naɪt/" },
    { word: "sun", meaning: "matahari", type: "noun", phonetic: "/sʌn/" },
    { word: "moon", meaning: "bulan", type: "noun", phonetic: "/muːn/" },
    { word: "star", meaning: "bintang", type: "noun", phonetic: "/stɑːr/" },
    { word: "sky", meaning: "langit", type: "noun", phonetic: "/skaɪ/" },
    { word: "rain", meaning: "hujan", type: "noun", phonetic: "/reɪn/" },
    { word: "tree", meaning: "pohon", type: "noun", phonetic: "/triː/" },
    { word: "flower", meaning: "bunga", type: "noun", phonetic: "/ˈflaʊ.ər/" },
    { word: "grass", meaning: "rumput", type: "noun", phonetic: "/ɡræs/" },
    { word: "animal", meaning: "hewan", type: "noun", phonetic: "/ˈæn.ɪ.məl/" },
    { word: "dog", meaning: "anjing", type: "noun", phonetic: "/dɒɡ/" },
    { word: "cat", meaning: "kucing", type: "noun", phonetic: "/kæt/" },
    { word: "bird", meaning: "burung", type: "noun", phonetic: "/bɜːrd/" },
    { word: "car", meaning: "mobil", type: "noun", phonetic: "/kɑːr/" },
    { word: "bike", meaning: "sepeda", type: "noun", phonetic: "/baɪk/" },
    { word: "bus", meaning: "bis", type: "noun", phonetic: "/bʌs/" },
    { word: "road", meaning: "jalan", type: "noun", phonetic: "/roʊd/" },
    { word: "city", meaning: "kota", type: "noun", phonetic: "/ˈsɪt.i/" },
    { word: "town", meaning: "kota kecil", type: "noun", phonetic: "/taʊn/" },
    { word: "street", meaning: "jalan raya", type: "noun", phonetic: "/striːt/" },
    { word: "shop", meaning: "toko", type: "noun", phonetic: "/ʃɒp/" },
    { word: "market", meaning: "pasar", type: "noun", phonetic: "/ˈmɑːr.kɪt/" },
    { word: "phone", meaning: "telepon", type: "noun", phonetic: "/foʊn/" },
    { word: "computer", meaning: "komputer", type: "noun", phonetic: "/kəmˈpjuː.tər/" },
    { word: "key", meaning: "kunci", type: "noun", phonetic: "/kiː/" },
    { word: "table", meaning: "meja", type: "noun", phonetic: "/ˈteɪ.bəl/" },
    { word: "lamp", meaning: "lampu", type: "noun", phonetic: "/læmp/" },
    { word: "clock", meaning: "jam", type: "noun", phonetic: "/klɒk/" },
    { word: "watch", meaning: "jam tangan", type: "noun", phonetic: "/wɒtʃ/" },
    { word: "box", meaning: "kotak", type: "noun", phonetic: "/bɒks/" },
    { word: "picture", meaning: "gambar/foto", type: "noun", phonetic: "/ˈpɪk.tʃər/" },
    { word: "movie", meaning: "film", type: "noun", phonetic: "/ˈmuː.vi/" },
    { word: "song", meaning: "lagu", type: "noun", phonetic: "/sɒŋ/" },
    { word: "game", meaning: "permainan", type: "noun", phonetic: "/ɡeɪm/" },
    { id: "n101", word: "breakfast", meaning: "sarapan", type: "noun", phonetic: "/ˈbrek.fəst/" },
    { id: "n102", word: "lunch", meaning: "makan siang", type: "noun", phonetic: "/lʌntʃ/" },
    { id: "n103", word: "dinner", meaning: "makan malam", type: "noun", phonetic: "/ˈdɪn.ər/" },
    { id: "n104", word: "office", meaning: "kantor", type: "noun", phonetic: "/ˈɒf.ɪs/" },
    { id: "n105", word: "hospital", meaning: "rumah sakit", type: "noun", phonetic: "/ˈhɒs.pɪ.təl/" },
    { id: "n106", word: "bank", meaning: "bank", type: "noun", phonetic: "/bæŋk/" },
    { id: "n107", word: "park", meaning: "taman", type: "noun", phonetic: "/pɑːrk/" },
    { id: "n108", word: "beach", meaning: "pantai", type: "noun", phonetic: "/biːtʃ/" },
    { id: "n109", word: "morning", meaning: "pagi", type: "noun", phonetic: "/ˈmɔːr.nɪŋ/" },
    { id: "n110", word: "afternoon", meaning: "siang/sore", type: "noun", phonetic: "/ˌæf.təˈnuːn/" },
    { id: "n111", word: "evening", meaning: "malam (awal)", type: "noun", phonetic: "/ˈiːv.nɪŋ/" },
    { id: "n112", word: "week", meaning: "minggu (7 hari)", type: "noun", phonetic: "/wiːk/" },
    { id: "n113", word: "month", meaning: "bulan (kalender)", type: "noun", phonetic: "/mʌnθ/" },
    { id: "n114", word: "year", meaning: "tahun", type: "noun", phonetic: "/jɪər/" },
    { id: "n115", word: "color", meaning: "warna", type: "noun", phonetic: "/ˈkʌl.ər/" },
    { id: "n116", word: "red", meaning: "merah", type: "noun", phonetic: "/red/" },
    { id: "n117", word: "blue", meaning: "biru", type: "noun", phonetic: "/bluː/" },
    { id: "n118", word: "green", meaning: "hijau", type: "noun", phonetic: "/ɡriːn/" },
    { id: "n119", word: "yellow", meaning: "kuning", type: "noun", phonetic: "/ˈjel.oʊ/" },
    { id: "n120", word: "black", meaning: "hitam", type: "noun", phonetic: "/blæk/" },
    { id: "n121", word: "white", meaning: "putih", type: "noun", phonetic: "/waɪt/" },
    { id: "n122", word: "job", meaning: "pekerjaan", type: "noun", phonetic: "/dʒɒb/" },
    { id: "n123", word: "doctor", meaning: "dokter", type: "noun", phonetic: "/ˈdɒk.tər/" },
    { id: "n124", word: "nurse", meaning: "perawat", type: "noun", phonetic: "/nɜːrs/" },
    { id: "n125", word: "farmer", meaning: "petani", type: "noun", phonetic: "/ˈfɑːr.mər/" },
    { id: "n126", word: "police", meaning: "polisi", type: "noun", phonetic: "/pəˈliːs/" },
    { id: "n127", word: "chef", meaning: "koki", type: "noun", phonetic: "/ʃef/" },
    { id: "n128", word: "pilot", meaning: "pilot", type: "noun", phonetic: "/ˈpaɪ.lət/" },
    { id: "n129", word: "driver", meaning: "sopir", type: "noun", phonetic: "/ˈdraɪ.vər/" },
    { id: "n130", word: "singer", meaning: "penyanyi", type: "noun", phonetic: "/ˈsɪŋ.ər/" },

    // --- DESCRIPTIONS / ADJECTIVES (80 Kata) ---
    { word: "happy", meaning: "senang", type: "adjective", phonetic: "/ˈhæp.i/" },
    { word: "sad", meaning: "sedih", type: "adjective", phonetic: "/sæd/" },
    { word: "big", meaning: "besar", type: "adjective", phonetic: "/bɪɡ/" },
    { word: "small", meaning: "kecil", type: "adjective", phonetic: "/smɔːl/" },
    { word: "good", meaning: "baik", type: "adjective", phonetic: "/ɡʊd/" },
    { word: "bad", meaning: "buruk", type: "adjective", phonetic: "/bæd/" },
    { word: "hot", meaning: "panas", type: "adjective", phonetic: "/hɒt/" },
    { word: "cold", meaning: "dingin", type: "adjective", phonetic: "/koʊld/" },
    { word: "hungry", meaning: "lapar", type: "adjective", phonetic: "/ˈhʌŋ.ɡri/" },
    { word: "thirsty", meaning: "haus", type: "adjective", phonetic: "/ˈθɜːr.sti/" },
    { word: "tired", meaning: "lelah", type: "adjective", phonetic: "/taɪərd/" },
    { word: "sleepy", meaning: "mengantuk", type: "adjective", phonetic: "/ˈsliː.pi/" },
    { word: "new", meaning: "baru", type: "adjective", phonetic: "/njuː/" },
    { word: "old", meaning: "lama/tua", type: "adjective", phonetic: "/oʊld/" },
    { word: "fast", meaning: "cepat", type: "adjective", phonetic: "/fæst/" },
    { word: "slow", meaning: "lambat", type: "adjective", phonetic: "/sloʊ/" },
    { word: "long", meaning: "panjang", type: "adjective", phonetic: "/lɒŋ/" },
    { word: "short", meaning: "pendek", type: "adjective", phonetic: "/ʃɔːrt/" },
    { word: "tall", meaning: "tinggi (badan)", type: "adjective", phonetic: "/tɔːl/" },
    { word: "high", meaning: "tinggi (benda)", type: "adjective", phonetic: "/haɪ/" },
    { word: "low", meaning: "rendah", type: "adjective", phonetic: "/loʊ/" },
    { word: "easy", meaning: "mudah", type: "adjective", phonetic: "/ˈiː.zi/" },
    { word: "hard", meaning: "sulit/keras", type: "adjective", phonetic: "/hɑːrd/" },
    { word: "difficult", meaning: "sulit", type: "adjective", phonetic: "/ˈdɪf.ɪ.kəlt/" },
    { word: "clean", meaning: "bersih", type: "adjective", phonetic: "/kliːn/" },
    { word: "dirty", meaning: "kotor", type: "adjective", phonetic: "/ˈdɜː.ti/" },
    { word: "rich", meaning: "kaya", type: "adjective", phonetic: "/rɪtʃ/" },
    { word: "poor", meaning: "miskin", type: "adjective", phonetic: "/pɔːr/" },
    { word: "strong", meaning: "kuat", type: "adjective", phonetic: "/strɒŋ/" },
    { word: "weak", meaning: "lemah", type: "adjective", phonetic: "/wiːk/" },
    { word: "smart", meaning: "pintar", type: "adjective", phonetic: "/smɑːrt/" },
    { word: "beautiful", meaning: "cantik", type: "adjective", phonetic: "/ˈbjuː.tɪ.fəl/" },
    { word: "handsome", meaning: "tampan", type: "adjective", phonetic: "/ˈhæn.səm/" },
    { word: "angry", meaning: "marah", type: "adjective", phonetic: "/ˈæŋ.ɡri/" },
    { word: "brave", meaning: "berani", type: "adjective", phonetic: "/breɪv/" },
    { word: "scared", meaning: "takut", type: "adjective", phonetic: "/skerd/" },
    { word: "quiet", meaning: "tenang/diam", type: "adjective", phonetic: "/ˈkwaɪ.ət/" },
    { word: "noisy", meaning: "berisik", type: "adjective", phonetic: "/ˈnɔɪ.zi/" },
    { word: "heavy", meaning: "berat", type: "adjective", phonetic: "/ˈhev.i/" },
    { word: "light", meaning: "ringan", type: "adjective", phonetic: "/laɪt/" },
    { id: "a41", word: "expensive", meaning: "mahal", type: "adjective", phonetic: "/ɪkˈspen.sɪv/" },
    { id: "a42", word: "cheap", meaning: "murah", type: "adjective", phonetic: "/tʃiːp/" },
    { id: "a43", word: "funny", meaning: "lucu", type: "adjective", phonetic: "/ˈfʌn.i/" },
    { id: "a44", word: "sweet", meaning: "manis", type: "adjective", phonetic: "/swiːt/" },
    { id: "a45", word: "sour", meaning: "asam", type: "adjective", phonetic: "/ˈsaʊ.ər/" },
    { id: "a46", word: "bitter", meaning: "pahit", type: "adjective", phonetic: "/ˈbɪt.ər/" },
    { id: "a47", word: "spicy", meaning: "pedas", type: "adjective", phonetic: "/ˈspaɪ.si/" },
    { id: "a48", word: "dark", meaning: "gelap", type: "adjective", phonetic: "/dɑːrk/" },
    { id: "a49", word: "bright", meaning: "terang", type: "adjective", phonetic: "/braɪt/" },
    { id: "a50", word: "soft", meaning: "lembut", type: "adjective", phonetic: "/sɒft/" },
    { id: "a51", word: "hard", meaning: "keras", type: "adjective", phonetic: "/hɑːrd/" },
    { id: "a52", word: "dry", meaning: "kering", type: "adjective", phonetic: "/draɪ/" },
    { id: "a53", word: "wet", meaning: "basah", type: "adjective", phonetic: "/wet/" },
    { id: "a54", word: "busy", meaning: "sibuk", type: "adjective", phonetic: "/ˈbɪz.i/" },
    { id: "a55", word: "lazy", meaning: "malas", type: "adjective", phonetic: "/ˈleɪ.zi/" },
    { id: "a56", word: "kind", meaning: "baik hati", type: "adjective", phonetic: "/kaɪnd/" },
    { id: "a57", word: "mean", meaning: "jahat/pelit", type: "adjective", phonetic: "/miːn/" },
    { id: "a58", word: "honest", meaning: "jujur", type: "adjective", phonetic: "/ˈɒn.ɪst/" },
    { id: "a59", word: "famous", meaning: "terkenal", type: "adjective", phonetic: "/ˈfeɪ.məs/" },
    { id: "a60", word: "important", meaning: "penting", type: "adjective", phonetic: "/ɪmˈpɔːr.tənt/" },
    { id: "a61", word: "ready", meaning: "siap", type: "adjective", phonetic: "/ˈred.i/" },
    { id: "a62", word: "wrong", meaning: "salah", type: "adjective", phonetic: "/rɒŋ/" },
    { id: "a63", word: "correct", meaning: "benar", type: "adjective", phonetic: "/kəˈrekt/" },
    { id: "a64", word: "boring", meaning: "membosankan", type: "adjective", phonetic: "/ˈbɔː.rɪŋ/" },
    { id: "a65", word: "exciting", meaning: "menyenangkan/seru", type: "adjective", phonetic: "/ɪkˈsaɪ.tɪŋ/" },
    { id: "a66", word: "empty", meaning: "kosong", type: "adjective", phonetic: "/ˈemp.ti/" },
    { id: "a67", word: "full", meaning: "penuh", type: "adjective", phonetic: "/fʊl/" },
    { id: "a68", word: "simple", meaning: "sederhana", type: "adjective", phonetic: "/ˈsɪm.pəl/" },
    { id: "a69", word: "safe", meaning: "aman", type: "adjective", phonetic: "/seɪf/" },
    { id: "a70", word: "dangerous", meaning: "berbahaya", type: "adjective", phonetic: "/ˈdeɪn.dʒər.əs/" },
    { id: "a71", word: "near", meaning: "dekat", type: "adjective", phonetic: "/nɪər/" },
    { id: "a72", word: "far", meaning: "jauh", type: "adjective", phonetic: "/fɑːr/" },
    { id: "a73", word: "young", meaning: "muda", type: "adjective", phonetic: "/jʌŋ/" },
    { id: "a74", word: "calm", meaning: "tenang", type: "adjective", phonetic: "/kɑːm/" },
    { id: "a75", word: "friendly", meaning: "ramah", type: "adjective", phonetic: "/ˈfrend.li/" },
    { id: "a76", word: "lucky", meaning: "beruntung", type: "adjective", phonetic: "/ˈlʌk.i/" },
    { id: "a77", word: "perfect", meaning: "sempurna", type: "adjective", phonetic: "/ˈpɜːr.fekt/" },
    { id: "a78", word: "deep", meaning: "dalam", type: "adjective", phonetic: "/diːp/" },
    { id: "a79", word: "shallow", meaning: "dangkal", type: "adjective", phonetic: "/ˈʃæl.oʊ/" },
    { id: "a80", word: "useful", meaning: "berguna", type: "adjective", phonetic: "/ˈjuːs.fəl/" }
];