/**
 * LINGUAQUEST - VOCABULARY BANK LEVEL 2 (300 WORDS)
 * Kategori: Menengah Dasar (Travel, Nature, Professions, Social Activities)
 */

window.VOCAB_MASTER = window.VOCAB_MASTER || {};

window.VOCAB_MASTER.LV2 = [
    // --- ACTIONS / VERBS (90 Kata) ---
    { word: "travel", meaning: "bepergian", type: "verb", phonetic: "/ˈtræv.əl/" },
    { word: "arrive", meaning: "sampai/tiba", type: "verb", phonetic: "/əˈraɪv/" },
    { word: "depart", meaning: "berangkat", type: "verb", phonetic: "/dɪˈpɑːrt/" },
    { word: "decide", meaning: "memutuskan", type: "verb", phonetic: "/dɪˈsaɪd/" },
    { word: "explain", meaning: "menjelaskan", type: "verb", phonetic: "/ɪkˈspleɪn/" },
    { word: "understand", meaning: "mengerti", type: "verb", phonetic: "/ˌʌn.dəˈstænd/" },
    { word: "remember", meaning: "ingat", type: "verb", phonetic: "/rɪˈmem.bər/" },
    { word: "forget", meaning: "lupa", type: "verb", phonetic: "/fəˈɡet/" },
    { word: "believe", meaning: "percaya", type: "verb", phonetic: "/bɪˈliːv/" },
    { word: "promise", meaning: "berjanji", type: "verb", phonetic: "/ˈprɒm.ɪs/" },
    { word: "prepare", meaning: "menyiapkan", type: "verb", phonetic: "/prɪˈper/" },
    { word: "improve", meaning: "meningkatkan", type: "verb", phonetic: "/ɪmˈpruːv/" },
    { word: "continue", meaning: "melanjutkan", type: "verb", phonetic: "/kənˈtɪn.juː/" },
    { word: "receive", meaning: "menerima", type: "verb", phonetic: "/rɪˈsiːv/" },
    { word: "deliver", meaning: "mengirim", type: "verb", phonetic: "/dɪˈlɪv.ər/" },
    { word: "search", meaning: "mencari", type: "verb", phonetic: "/sɜːrtʃ/" },
    { word: "discover", meaning: "menemukan", type: "verb", phonetic: "/dɪˈskʌv.ər/" },
    { word: "create", meaning: "menciptakan", type: "verb", phonetic: "/kriˈeɪt/" },
    { word: "design", meaning: "merancang", type: "verb", phonetic: "/dɪˈzaɪn/" },
    { word: "repair", meaning: "memperbaiki", type: "verb", phonetic: "/rɪˈper/" },
    { word: "invite", meaning: "mengundang", type: "verb", phonetic: "/ɪnˈvaɪt/" },
    { word: "join", meaning: "bergabung", type: "verb", phonetic: "/dʒɔɪn/" },
    { word: "follow", meaning: "mengikuti", type: "verb", phonetic: "/ˈfɒl.oʊ/" },
    { word: "lead", meaning: "memimpin", type: "verb", phonetic: "/liːd/" },
    { word: "save", meaning: "menabung/menyelamatkan", type: "verb", phonetic: "/seɪv/" },
    { word: "spend", meaning: "menghabiskan", type: "verb", phonetic: "/spend/" },
    { word: "earn", meaning: "menghasilkan (uang)", type: "verb", phonetic: "/ɜːrn/" },
    { word: "borrow", meaning: "meminjam", type: "verb", phonetic: "/ˈbɒr.oʊ/" },
    { word: "lend", meaning: "meminjamkan", type: "verb", phonetic: "/lend/" },
    { word: "choose", meaning: "memilih", type: "verb", phonetic: "/tʃuːz/" },
    { word: "agree", meaning: "setuju", type: "verb", phonetic: "/əˈɡriː/" },
    { word: "complain", meaning: "mengeluh", type: "verb", phonetic: "/kəmˈpleɪn/" },
    { word: "suggest", meaning: "menyarankan", type: "verb", phonetic: "/səˈdʒest/" },
    { word: "expect", meaning: "mengharap", type: "verb", phonetic: "/ɪkˈspekt/" },
    { word: "realize", meaning: "menyadari", type: "verb", phonetic: "/ˈriː.ə.laɪz/" },
    { word: "wonder", meaning: "bertanya-tanya", type: "verb", phonetic: "/ˈwʌn.dər/" },
    { word: "prefer", meaning: "lebih suka", type: "verb", phonetic: "/prɪˈfɜːr/" },
    { word: "enjoy", meaning: "menikmati", type: "verb", phonetic: "/ɪnˈdʒɔɪ/" },
    { word: "imagine", meaning: "membayangkan", type: "verb", phonetic: "/ɪˈmædʒ.ɪn/" },
    { word: "belong", meaning: "milik", type: "verb", phonetic: "/bɪˈlɒŋ/" },
    { word: "contain", meaning: "berisi", type: "verb", phonetic: "/kənˈteɪn/" },
    { word: "protect", meaning: "melindungi", type: "verb", phonetic: "/prəˈtekt/" },
    { word: "prevent", meaning: "mencegah", type: "verb", phonetic: "/prɪˈvent/" },
    { word: "support", meaning: "mendukung", type: "verb", phonetic: "/səˈpɔːrt/" },
    { word: "control", meaning: "mengendalikan", type: "verb", phonetic: "/kənˈtroʊl/" },
    { word: "measure", meaning: "mengukur", type: "verb", phonetic: "/ˈmeʒ.ər/" },
    { word: "increase", meaning: "bertambah", type: "verb", phonetic: "/ɪnˈkriːs/" },
    { word: "decrease", meaning: "berkurang", type: "verb", phonetic: "/dɪˈkriːs/" },
    { word: "fly", meaning: "terbang", type: "verb", phonetic: "/flaɪ/" },
    { word: "climb", meaning: "memanjat", type: "verb", phonetic: "/klaɪm/" },
    { word: "explore", meaning: "menjelajah", type: "verb", phonetic: "/ɪkˈsplɔːr/" },
    { word: "happen", meaning: "terjadi", type: "verb", phonetic: "/ˈhæp.ən/" },
    { word: "appear", meaning: "muncul", type: "verb", phonetic: "/əˈpɪər/" },
    { word: "disappear", meaning: "menghilang", type: "verb", phonetic: "/ˌdɪs.əˈpɪər/" },
    { word: "solve", meaning: "memecahkan (masalah)", type: "verb", phonetic: "/sɒlv/" },
    { word: "develop", meaning: "mengembangkan", type: "verb", phonetic: "/dɪˈvel.əp/" },
    { word: "organize", meaning: "mengatur", type: "verb", phonetic: "/ˈɔːr.ɡən.aɪz/" },
    { word: "manage", meaning: "mengelola", type: "verb", phonetic: "/ˈmæn.ɪdʒ/" },
    { word: "replace", meaning: "mengganti", type: "verb", phonetic: "/rɪˈpleɪs/" },
    { word: "return", meaning: "kembali", type: "verb", phonetic: "/rɪˈtɜːrn/" },
    { word: "exchange", meaning: "bertukar", type: "verb", phonetic: "/ɪksˈtʃeɪndʒ/" },
    { word: "share", meaning: "berbagi", type: "verb", phonetic: "/ʃer/" },
    { word: "accept", meaning: "menerima", type: "verb", phonetic: "/əkˈsept/" },
    { word: "refuse", meaning: "menolak", type: "verb", phonetic: "/rɪˈfjuːz/" },
    { word: "ignore", meaning: "mengabaikan", type: "verb", phonetic: "/ɪɡˈnɔːr/" },
    { word: "notice", meaning: "memperhatikan", type: "verb", phonetic: "/ˈnoʊ.tɪs/" },
    { word: "warn", meaning: "memperingatkan", type: "verb", phonetic: "/wɔːrn/" },
    { word: "encourage", meaning: "mendorong/menyemangati", type: "verb", phonetic: "/ɪnˈkʌr.ɪdʒ/" },
    { word: "describe", meaning: "mendeskripsikan", type: "verb", phonetic: "/dɪˈskraɪb/" },
    { word: "identify", meaning: "mengidentifikasi", type: "verb", phonetic: "/aɪˈden.tɪ.faɪ/" },
    { word: "produce", meaning: "menghasilkan", type: "verb", phonetic: "/prəˈduːs/" },
    { word: "connect", meaning: "menghubungkan", type: "verb", phonetic: "/kəˈnekt/" },
    { word: "separate", meaning: "memisahkan", type: "verb", phonetic: "/ˈsep.ər.eɪt/" },
    { word: "provide", meaning: "menyediakan", type: "verb", phonetic: "/prəˈvaɪd/" },
    { word: "offer", meaning: "menawarkan", type: "verb", phonetic: "/ˈɒf.ər/" },
    { word: "serve", meaning: "melayani", type: "verb", phonetic: "/sɜːrv/" },
    { word: "gather", meaning: "berkumpul", type: "verb", phonetic: "/ˈɡæð.ər/" },
    { word: "celebrate", meaning: "merayakan", type: "verb", phonetic: "/ˈsel.ə.breɪt/" },
    { word: "greet", meaning: "menyapa", type: "verb", phonetic: "/ɡriːt/" },
    { word: "introduce", meaning: "memperkenalkan", type: "verb", phonetic: "/ˌɪn.trəˈduːs/" },
    { word: "advise", meaning: "menasihati", type: "verb", phonetic: "/ədˈvaɪz/" },
    { word: "argue", meaning: "berdebat", type: "verb", phonetic: "/ˈɑːr.ɡjuː/" },
    { word: "compete", meaning: "bersaing", type: "verb", phonetic: "/kəmˈpiːt/" },
    { word: "avoid", meaning: "menghindari", type: "verb", phonetic: "/əˈvɔɪd/" },
    { word: "fit", meaning: "cocok/muat", type: "verb", phonetic: "/fɪt/" },
    { word: "suit", meaning: "sesuai", type: "verb", phonetic: "/suːt/" },
    { word: "match", meaning: "mencocokkan", type: "verb", phonetic: "/mætʃ/" },
    { word: "kick", meaning: "menendang", type: "verb", phonetic: "/kɪk/" },
    { word: "score", meaning: "mencetak skor", type: "verb", phonetic: "/skɔːr/" },
    { word: "win", meaning: "menang", type: "verb", phonetic: "/wɪn/" },

    // --- NOUNS / PLACES / PROFESSIONS (130 Kata) ---
    { word: "airport", meaning: "bandara", type: "noun", phonetic: "/ˈer.pɔːrt/" },
    { word: "station", meaning: "stasiun", type: "noun", phonetic: "/ˈsteɪ.ʃən/" },
    { word: "museum", meaning: "museum", type: "noun", phonetic: "/mjuːˈziː.əm/" },
    { word: "library", meaning: "perpustakaan", type: "noun", phonetic: "/ˈlaɪ.brer.i/" },
    { word: "beach", meaning: "pantai", type: "noun", phonetic: "/biːtʃ/" },
    { word: "mountain", meaning: "gunung", type: "noun", phonetic: "/ˈmaʊn.tɪn/" },
    { word: "forest", meaning: "hutan", type: "noun", phonetic: "/ˈfɒr.ɪst/" },
    { word: "island", meaning: "pulau", type: "noun", phonetic: "/ˈaɪ.lənd/" },
    { word: "river", meaning: "sungai", type: "noun", phonetic: "/ˈrɪv.ər/" },
    { word: "ocean", meaning: "samudra", type: "noun", phonetic: "/ˈoʊ.ʃən/" },
    { word: "bridge", meaning: "jembatan", type: "noun", phonetic: "/brɪdʒ/" },
    { word: "palace", meaning: "istana", type: "noun", phonetic: "/ˈpæl.əs/" },
    { word: "temple", meaning: "kuil/candi", type: "noun", phonetic: "/ˈtem.pəl/" },
    { word: "university", meaning: "universitas", type: "noun", phonetic: "/ˌjuː.nɪˈvɜːr.sə.ti/" },
    { word: "office", meaning: "kantor", type: "noun", phonetic: "/ˈɒf.ɪs/" },
    { word: "company", meaning: "perusahaan", type: "noun", phonetic: "/ˈkʌm.pə.ni/" },
    { word: "factory", meaning: "pabrik", type: "noun", phonetic: "/ˈfæk.tər.i/" },
    { word: "stadium", meaning: "stadion", type: "noun", phonetic: "/ˈsteɪ.di.əm/" },
    { word: "theater", meaning: "teater", type: "noun", phonetic: "/ˈθiː.ə.tər/" },
    { word: "hotel", meaning: "hotel", type: "noun", phonetic: "/hoʊˈtel/" },
    { word: "restaurant", meaning: "restoran", type: "noun", phonetic: "/ˈres.trɒnt/" },
    { word: "bakery", meaning: "toko roti", type: "noun", phonetic: "/ˈbeɪ.kər.i/" },
    { word: "pharmacy", meaning: "apotek", type: "noun", phonetic: "/ˈfɑːr.mə.si/" },
    { word: "gym", meaning: "tempat senam", type: "noun", phonetic: "/dʒɪm/" },
    { word: "planet", meaning: "planet", type: "noun", phonetic: "/ˈplæn.ɪt/" },
    { word: "space", meaning: "luar angkasa", type: "noun", phonetic: "/speɪs/" },
    { word: "weather", meaning: "cuaca", type: "noun", phonetic: "/ˈweð.ər/" },
    { word: "storm", meaning: "badai", type: "noun", phonetic: "/stɔːrm/" },
    { word: "thunder", meaning: "guntur", type: "noun", phonetic: "/ˈθʌn.dər/" },
    { word: "lightning", meaning: "kilat", type: "noun", phonetic: "/ˈlaɪt.nɪŋ/" },
    { word: "climate", meaning: "iklim", type: "noun", phonetic: "/ˈklaɪ.mət/" },
    { word: "temperature", meaning: "suhu", type: "noun", phonetic: "/ˈtem.prə.tʃər/" },
    { word: "nature", meaning: "alam", type: "noun", phonetic: "/ˈneɪ.tʃər/" },
    { word: "wildlife", meaning: "kehidupan liar", type: "noun", phonetic: "/ˈwaɪld.laɪf/" },
    { word: "environment", meaning: "lingkungan", type: "noun", phonetic: "/ɪnˈvaɪ.rən.mənt/" },
    { word: "pollution", meaning: "polusi", type: "noun", phonetic: "/pəˈluː.ʃən/" },
    { word: "government", meaning: "pemerintah", type: "noun", phonetic: "/ˈɡʌv.ən.mənt/" },
    { word: "president", meaning: "presiden", type: "noun", phonetic: "/ˈprez.ɪ.dənt/" },
    { word: "citizen", meaning: "warga negara", type: "noun", phonetic: "/ˈsɪt.ɪ.zən/" },
    { word: "soldier", meaning: "tentara", type: "noun", phonetic: "/ˈsoʊl.dʒər/" },
    { word: "officer", meaning: "petugas/perwira", type: "noun", phonetic: "/ˈɒf.ɪ.sər/" },
    { word: "engineer", meaning: "insinyur", type: "noun", phonetic: "/ˌen.dʒɪˈnɪər/" },
    { word: "scientist", meaning: "ilmuwan", type: "noun", phonetic: "/ˈsaɪ.ən.tɪst/" },
    { word: "journalist", meaning: "wartawan", type: "noun", phonetic: "/ˈdʒɜːr.nə.lɪst/" },
    { word: "photographer", meaning: "fotografer", type: "noun", phonetic: "/fəˈtɒɡ.rə.fər/" },
    { word: "artist", meaning: "seniman", type: "noun", phonetic: "/ˈɑːr.tɪst/" },
    { word: "musician", meaning: "musisi", type: "noun", phonetic: "/mjuːˈzɪʃ.ən/" },
    { word: "actor", meaning: "aktor", type: "noun", phonetic: "/ˈæk.tər/" },
    { word: "lawyer", meaning: "pengacara", type: "noun", phonetic: "/ˈlɔɪ.ər/" },
    { word: "customer", meaning: "pelanggan", type: "noun", phonetic: "/ˈkʌs.tə.mər/" },
    { word: "manager", meaning: "manajer", type: "noun", phonetic: "/ˈmæn.ɪ.dʒər/" },
    { word: "employee", meaning: "karyawan", type: "noun", phonetic: "/ɪmˈplɔɪ.iː/" },
    { word: "business", meaning: "bisnis", type: "noun", phonetic: "/ˈbɪz.nɪs/" },
    { word: "project", meaning: "proyek", type: "noun", phonetic: "/ˈprɒdʒ.ekt/" },
    { word: "meeting", meaning: "rapat", type: "noun", phonetic: "/ˈmiː.tɪŋ/" },
    { word: "schedule", meaning: "jadwal", type: "noun", phonetic: "/ˈʃedʒ.uːl/" },
    { word: "report", meaning: "laporan", type: "noun", phonetic: "/rɪˈpɔːrt/" },
    { word: "advice", meaning: "nasihat", type: "noun", phonetic: "/ədˈvaɪs/" },
    { word: "opinion", meaning: "pendapat", type: "noun", phonetic: "/əˈpɪn.jən/" },
    { word: "decision", meaning: "keputusan", type: "noun", phonetic: "/dɪˈsɪʒ.ən/" },
    { word: "solution", meaning: "solusi", type: "noun", phonetic: "/səˈluː.ʃən/" },
    { word: "problem", meaning: "masalah", type: "noun", phonetic: "/ˈprɒb.ləm/" },
    { word: "experience", meaning: "pengalaman", type: "noun", phonetic: "/ɪkˈspɪə.ri.əns/" },
    { word: "memory", meaning: "ingatan", type: "noun", phonetic: "/ˈmem.ər.i/" },
    { word: "knowledge", meaning: "pengetahuan", type: "noun", phonetic: "/ˈnɒl.ɪdʒ/" },
    { word: "future", meaning: "masa depan", type: "noun", phonetic: "/ˈfjuː.tʃər/" },
    { word: "history", meaning: "sejarah", type: "noun", phonetic: "/ˈhɪs.tər.i/" },
    { word: "culture", meaning: "budaya", type: "noun", phonetic: "/ˈkʌl.tʃər/" },
    { word: "tradition", meaning: "tradisi", type: "noun", phonetic: "/trəˈdɪʃ.ən/" },
    { word: "language", meaning: "bahasa", type: "noun", phonetic: "/ˈlæŋ.ɡwɪdʒ/" },
    { word: "dictionary", meaning: "kamus", type: "noun", phonetic: "/ˈdɪk.ʃən.ər.i/" },
    { word: "magazine", meaning: "majalah", type: "noun", phonetic: "/ˌmæɡ.əˈziːn/" },
    { word: "newspaper", meaning: "koran", type: "noun", phonetic: "/ˈnjuːzˌpeɪ.pər/" },
    { word: "instruction", meaning: "instruksi", type: "noun", phonetic: "/ɪnˈstrʌk.ʃən/" },
    { word: "equipment", meaning: "peralatan", type: "noun", phonetic: "/ɪˈkwɪp.mənt/" },
    { word: "instrument", meaning: "instrumen", type: "noun", phonetic: "/ˈɪn.strə.mənt/" },
    { word: "technology", meaning: "teknologi", type: "noun", phonetic: "/tekˈnɒl.ə.dʒi/" },
    { word: "internet", meaning: "internet", type: "noun", phonetic: "/ˈɪn.tə.net/" },
    { word: "signal", meaning: "sinyal", type: "noun", phonetic: "/ˈsɪɡ.nəl/" },
    { word: "battery", meaning: "baterai", type: "noun", phonetic: "/ˈbæt.ər.i/" },
    { word: "journey", meaning: "perjalanan", type: "noun", phonetic: "/ˈdʒɜː.ni/" },
    { word: "adventure", meaning: "petualangan", type: "noun", phonetic: "/ədˈven.tʃər/" },
    { word: "ticket", meaning: "tiket", type: "noun", phonetic: "/ˈtɪk.ɪt/" },
    { word: "passport", meaning: "paspor", type: "noun", phonetic: "/ˈpɑːs.pɔːrt/" },
    { word: "suitcase", meaning: "koper", type: "noun", phonetic: "/ˈsuːt.keɪs/" },
    { word: "baggage", meaning: "bagasi", type: "noun", phonetic: "/ˈbæɡ.ɪdʒ/" },
    { word: "currency", meaning: "mata uang", type: "noun", phonetic: "/ˈkʌr.ən.si/" },
    { word: "price", meaning: "harga", type: "noun", phonetic: "/praɪs/" },
    { word: "discount", meaning: "diskon", type: "noun", phonetic: "/ˈdɪs.kaʊnt/" },
    { word: "receipt", meaning: "struk", type: "noun", phonetic: "/rɪˈsiːt/" },
    { word: "menu", meaning: "menu", type: "noun", phonetic: "/ˈmen.juː/" },
    { word: "ingredient", meaning: "bahan masakan", type: "noun", phonetic: "/ɪnˈɡriː.di.ənt/" },
    { word: "snack", meaning: "camilan", type: "noun", phonetic: "/snæk/" },
    { word: "dessert", meaning: "pencuci mulut", type: "noun", phonetic: "/dɪˈzɜːrt/" },
    { word: "medicine", meaning: "obat", type: "noun", phonetic: "/ˈmed.ɪ.sən/" },
    { word: "health", meaning: "kesehatan", type: "noun", phonetic: "/helθ/" },
    { word: "disease", meaning: "penyakit", type: "noun", phonetic: "/dɪˈziːz/" },
    { word: "accident", meaning: "kecelakaan", type: "noun", phonetic: "/ˈæk.sɪ.dənt/" },
    { word: "emergency", meaning: "darurat", type: "noun", phonetic: "/ɪˈmɜː.dʒən.si/" },
    { word: "safety", meaning: "keamanan", type: "noun", phonetic: "/ˈseɪf.ti/" },
    { word: "security", meaning: "keamanan (sistem)", type: "noun", phonetic: "/sɪˈkjʊə.rə.ti/" },
    { word: "truth", meaning: "kebenaran", type: "noun", phonetic: "/truːθ/" },
    { word: "lie", meaning: "kebohongan", type: "noun", phonetic: "/laɪ/" },
    { word: "secret", meaning: "rahasia", type: "noun", phonetic: "/ˈsiː.krət/" },
    { word: "shadow", meaning: "bayangan", type: "noun", phonetic: "/ˈʃæd.oʊ/" },
    { word: "mirror", meaning: "cermin", type: "noun", phonetic: "/ˈmɪr.ər/" },
    { word: "habit", meaning: "kebiasaan", type: "noun", phonetic: "/ˈhæb.ɪt/" },
    { word: "skill", meaning: "keterampilan", type: "noun", phonetic: "/skɪl/" },
    { word: "talent", meaning: "bakat", type: "noun", phonetic: "/ˈtæl.ənt/" },
    { word: "effort", meaning: "usaha", type: "noun", phonetic: "/ˈef.ət/" },
    { word: "goal", meaning: "tujuan", type: "noun", phonetic: "/ɡoʊl/" },
    { word: "success", meaning: "kesuksesan", type: "noun", phonetic: "/səkˈses/" },
    { word: "failure", meaning: "kegagalan", type: "noun", phonetic: "/ˈfeɪ.ljər/" },
    { word: "victory", meaning: "kemenangan", type: "noun", phonetic: "/ˈvɪk.tər.i/" },
    { word: "competition", meaning: "kompetisi", type: "noun", phonetic: "/ˌkɒm.pəˈtɪʃ.ən/" },
    { word: "audience", meaning: "penonton", type: "noun", phonetic: "/ˈɔː.di.əns/" },
    { word: "celebrity", meaning: "selebriti", type: "noun", phonetic: "/səˈleb.rə.ti/" },
    { word: "fashion", meaning: "mode", type: "noun", phonetic: "/ˈfæʃ.ən/" },
    { word: "jewelry", meaning: "perhiasan", type: "noun", phonetic: "/ˈdʒuː.əl.ri/" },
    { word: "plastic", meaning: "plastik", type: "noun", phonetic: "/ˈplæs.tɪk/" },
    { word: "metal", meaning: "logam", type: "noun", phonetic: "/ˈmet.əl/" },
    { word: "wood", meaning: "kayu", type: "noun", phonetic: "/wʊd/" },
    { word: "glass", meaning: "kaca", type: "noun", phonetic: "/ɡlæs/" },
    { word: "stone", meaning: "batu", type: "noun", phonetic: "/stoʊn/" },
    { word: "sand", meaning: "pasir", type: "noun", phonetic: "/sænd/" },
    { word: "soil", meaning: "tanah", type: "noun", phonetic: "/sɔɪl/" },
    { word: "root", meaning: "akar", type: "noun", phonetic: "/ruːt/" },
    { word: "leaf", meaning: "daun", type: "noun", phonetic: "/liːf/" },
    { word: "branch", meaning: "cabang", type: "noun", phonetic: "/brɑːntʃ/" },
    { word: "feather", meaning: "bulu burung", type: "noun", phonetic: "/ˈfeð.ər/" },

    // --- ADJECTIVES (80 Kata) ---
    { word: "comfortable", meaning: "nyaman", type: "adjective", phonetic: "/ˈkʌm.fə.tə.bəl/" },
    { word: "valuable", meaning: "berharga", type: "adjective", phonetic: "/ˈvæl.jə.bəl/" },
    { word: "suitable", meaning: "cocok", type: "adjective", phonetic: "/ˈsuː.tə.bəl/" },
    { word: "available", meaning: "tersedia", type: "adjective", phonetic: "/əˈveɪ.lə.bəl/" },
    { word: "possible", meaning: "mungkin", type: "adjective", phonetic: "/ˈpɒs.ə.bəl/" },
    { word: "impossible", meaning: "tidak mungkin", type: "adjective", phonetic: "/ɪmˈpɒs.ə.bəl/" },
    { word: "responsible", meaning: "bertanggung jawab", type: "adjective", phonetic: "/rɪˈspɒn.sə.bəl/" },
    { word: "careful", meaning: "hati-hati", type: "adjective", phonetic: "/ˈker.fəl/" },
    { word: "careless", meaning: "ceroboh", type: "adjective", phonetic: "/ˈker.ləs/" },
    { word: "useful", meaning: "berguna", type: "adjective", phonetic: "/ˈjuːs.fəl/" },
    { word: "useless", meaning: "tidak berguna", type: "adjective", phonetic: "/ˈjuːs.ləs/" },
    { word: "wonderful", meaning: "luar biasa", type: "adjective", phonetic: "/ˈwʌn.də.fəl/" },
    { word: "terrible", meaning: "mengerikan", type: "adjective", phonetic: "/ˈter.ə.bəl/" },
    { word: "popular", meaning: "populer", type: "adjective", phonetic: "/ˈpɒp.jə.lər/" },
    { word: "famous", meaning: "terkenal", type: "adjective", phonetic: "/ˈfeɪ.məs/" },
    { word: "ordinary", meaning: "biasa saja", type: "adjective", phonetic: "/ˈɔːr.dən.er.i/" },
    { word: "strange", meaning: "aneh", type: "adjective", phonetic: "/streɪndʒ/" },
    { word: "modern", meaning: "modern", type: "adjective", phonetic: "/ˈmɒd.ən/" },
    { word: "ancient", meaning: "kuno", type: "adjective", phonetic: "/ˈeɪn.ʃənt/" },
    { word: "national", meaning: "nasional", type: "adjective", phonetic: "/ˈnæʃ.ən.əl/" },
    { word: "international", meaning: "internasional", type: "adjective", phonetic: "/ˌɪn.təˈnæʃ.ən.əl/" },
    { word: "natural", meaning: "alami", type: "adjective", phonetic: "/ˈnætʃ.ər.əl/" },
    { word: "artificial", meaning: "buatan", type: "adjective", phonetic: "/ˌɑː.tɪˈfɪʃ.əl/" },
    { word: "actual", meaning: "sebenarnya", type: "adjective", phonetic: "/ˈæk.tʃu.əl/" },
    { word: "general", meaning: "umum", type: "adjective", phonetic: "/ˈdʒen.ər.əl/" },
    { word: "special", meaning: "khusus", type: "adjective", phonetic: "/ˈspeʃ.əl/" },
    { word: "private", meaning: "pribadi", type: "adjective", phonetic: "/ˈpraɪ.vət/" },
    { word: "public", meaning: "umum", type: "adjective", phonetic: "/ˈpʌb.lɪk/" },
    { word: "local", meaning: "lokal", type: "adjective", phonetic: "/ˈloʊ.kəl/" },
    { word: "global", meaning: "global", type: "adjective", phonetic: "/ˈɡloʊ.bəl/" },
    { word: "main", meaning: "utama", type: "adjective", phonetic: "/meɪn/" },
    { word: "final", meaning: "terakhir", type: "adjective", phonetic: "/ˈfaɪ.nəl/" },
    { word: "frequent", meaning: "sering", type: "adjective", phonetic: "/ˈfriː.kwənt/" },
    { word: "rare", meaning: "jarang", type: "adjective", phonetic: "/rer/" },
    { word: "silent", meaning: "hening", type: "adjective", phonetic: "/ˈsaɪ.lənt/" },
    { word: "loud", meaning: "keras (suara)", type: "adjective", phonetic: "/laʊd/" },
    { word: "neat", meaning: "rapi", type: "adjective", phonetic: "/niːt/" },
    { word: "messy", meaning: "berantakan", type: "adjective", phonetic: "/ˈmes.i/" },
    { word: "wild", meaning: "liar", type: "adjective", phonetic: "/waɪld/" },
    { word: "tame", meaning: "jinak", type: "adjective", phonetic: "/teɪm/" },
    { word: "brave", meaning: "berani", type: "adjective", phonetic: "/breɪv/" },
    { word: "coward", meaning: "penakut", type: "adjective", phonetic: "/ˈkaʊ.əd/" },
    { word: "generous", meaning: "dermawan", type: "adjective", phonetic: "/ˈdʒen.ər.əs/" },
    { word: "selfish", meaning: "egois", type: "adjective", phonetic: "/ˈsel.fɪʃ/" },
    { word: "patient", meaning: "sabar", type: "adjective", phonetic: "/ˈpeɪ.ʃənt/" },
    { word: "rude", meaning: "sopan/kasar", type: "adjective", phonetic: "/ruːd/" },
    { word: "polite", meaning: "sopan", type: "adjective", phonetic: "/pəˈlaɪt/" },
    { word: "honest", meaning: "jujur", type: "adjective", phonetic: "/ˈɒn.ɪst/" },
    { word: "proud", meaning: "bangga", type: "adjective", phonetic: "/praʊd/" },
    { word: "shameful", meaning: "memalukan", type: "adjective", phonetic: "/ˈʃeɪm.fəl/" },
    { word: "nervous", meaning: "gugup", type: "adjective", phonetic: "/ˈnɜː.vəs/" },
    { word: "confident", meaning: "percaya diri", type: "adjective", phonetic: "/ˈkɒn.fɪ.dənt/" },
    { word: "lonely", meaning: "kesepian", type: "adjective", phonetic: "/ˈloʊn.li/" },
    { word: "creative", meaning: "kreatif", type: "adjective", phonetic: "/kriˈeɪ.tɪv/" },
    { word: "serious", meaning: "serius", type: "adjective", phonetic: "/ˈsɪə.ri.əs/" },
    { word: "calm", meaning: "tenang", type: "adjective", phonetic: "/kɑːm/" },
    { word: "excited", meaning: "bersemangat", type: "adjective", phonetic: "/ɪkˈsaɪ.tɪd/" },
    { word: "bored", meaning: "bosan", type: "adjective", phonetic: "/bɔːrd/" },
    { word: "curious", meaning: "penasaran", type: "adjective", phonetic: "/ˈkjʊə.ri.əs/" },
    { word: "surprised", meaning: "terkejut", type: "adjective", phonetic: "/səˈpraɪzd/" },
    { word: "awake", meaning: "terjaga", type: "adjective", phonetic: "/əˈweɪk/" },
    { word: "alive", meaning: "hidup", type: "adjective", phonetic: "/əˈlaɪv/" },
    { word: "dead", meaning: "mati", type: "adjective", phonetic: "/ded/" },
    { word: "flat", meaning: "datar", type: "adjective", phonetic: "/flæt/" },
    { word: "sharp", meaning: "tajam", type: "adjective", phonetic: "/ʃɑːrp/" },
    { word: "dull", meaning: "tumpul", type: "adjective", phonetic: "/dʌl/" },
    { word: "thick", meaning: "tebal", type: "adjective", phonetic: "/θɪk/" },
    { word: "thin", meaning: "tipis", type: "adjective", phonetic: "/θɪn/" },
    { word: "wide", meaning: "lebar", type: "adjective", phonetic: "/waɪd/" },
    { word: "narrow", meaning: "sempit", type: "adjective", phonetic: "/ˈnær.oʊ/" },
    { word: "heavy", meaning: "berat", type: "adjective", phonetic: "/ˈhev.i/" },
    { word: "light", meaning: "ringan", type: "adjective", phonetic: "/laɪt/" },
    { word: "smooth", meaning: "halus", type: "adjective", phonetic: "/smuːð/" },
    { word: "rough", meaning: "kasar", type: "adjective", phonetic: "/rʌf/" },
    { word: "expensive", meaning: "mahal", type: "adjective", phonetic: "/ɪkˈspen.sɪv/" },
    { word: "cheap", meaning: "murah", type: "adjective", phonetic: "/tʃiːp/" },
    { word: "rich", meaning: "kaya", type: "adjective", phonetic: "/rɪtʃ/" },
    { word: "poor", meaning: "miskin", type: "adjective", phonetic: "/pɔːr/" },
    { word: "official", meaning: "resmi", type: "adjective", phonetic: "/əˈfɪʃ.əl/" },
    { word: "illegal", meaning: "ilegal", type: "adjective", phonetic: "/ɪˈliː.ɡəl/" }
];