/**
 * LINGUAQUEST - VOCABULARY BANK LEVEL 5 (300 WORDS)
 * Kategori: Master (Academic, Nuanced, Formal & Sophisticated)
 */

window.VOCAB_MASTER = window.VOCAB_MASTER || {};

window.VOCAB_MASTER.LV5 = [
    // --- ACTIONS / VERBS (90 Kata) ---
    { word: "advocate", meaning: "menganjurkan/membela", type: "verb", phonetic: "/ˈæd.və.keɪt/" },
    { word: "alleviate", meaning: "meringankan", type: "verb", phonetic: "/əˈliː.vi.eɪt/" },
    { word: "ascertain", meaning: "memastikan", type: "verb", phonetic: "/ˌæs.əˈteɪn/" },
    { word: "collaborate", meaning: "berkolaborasi", type: "verb", phonetic: "/kəˈlæb.ə.reɪt/" },
    { word: "commence", meaning: "memulai (formal)", type: "verb", phonetic: "/kəˈmens/" },
    { word: "consolidate", meaning: "memperkuat/menggabungkan", type: "verb", phonetic: "/kənˈsɒl.ɪ.deɪt/" },
    { word: "contradict", meaning: "menyanggah", type: "verb", phonetic: "/ˌkɒn.trəˈdɪkt/" },
    { word: "corroborate", meaning: "menguatkan (bukti)", type: "verb", phonetic: "/kəˈrɒb.ə.reɪt/" },
    { word: "cultivate", meaning: "memupuk/mengembangkan", type: "verb", phonetic: "/ˈkʌl.tɪ.veɪt/" },
    { word: "deteriorate", meaning: "memburuk", type: "verb", phonetic: "/dɪˈtɪə.ri.ə.reɪt/" },
    { word: "deviate", meaning: "menyimpang", type: "verb", phonetic: "/ˈdiː.vi.eɪt/" },
    { word: "disseminate", meaning: "menyebarluaskan", type: "verb", phonetic: "/dɪˈsem.ɪ.neɪt/" },
    { word: "distinguish", meaning: "membedakan", type: "verb", phonetic: "/dɪˈstɪŋ.ɡwɪʃ/" },
    { word: "elaborate", meaning: "menguraikan", type: "verb", phonetic: "/iˈlæb.ər.eɪt/" },
    { word: "elucidate", meaning: "menjelaskan dengan gamblang", type: "verb", phonetic: "/iˈluː.sɪ.deɪt/" },
    { word: "embody", meaning: "mewujudkan", type: "verb", phonetic: "/ɪmˈbɒd.i/" },
    { word: "empower", meaning: "memberdayakan", type: "verb", phonetic: "/ɪmˈpaʊ.ər/" },
    { word: "endeavor", meaning: "berupaya keras", type: "verb", phonetic: "/ɪnˈdev.ər/" },
    { word: "enhance", meaning: "meningkatkan", type: "verb", phonetic: "/ɪnˈhɑːns/" },
    { word: "envisage", meaning: "membayangkan (masa depan)", type: "verb", phonetic: "/ɪnˈvɪz.ɪdʒ/" },
    { word: "eradicate", meaning: "memberantas", type: "verb", phonetic: "/ɪˈræd.ɪ.keɪt/" },
    { word: "evoke", meaning: "membangkitkan (perasaan)", type: "verb", phonetic: "/ɪˈvoʊk/" },
    { word: "exacerbate", meaning: "memperburuk (situasi)", type: "verb", phonetic: "/ɪɡˈzæs.ə.beɪt/" },
    { word: "examine", meaning: "memeriksa teliti", type: "verb", phonetic: "/ɪɡˈzæm.ɪn/" },
    { word: "exemplify", meaning: "memberi contoh", type: "verb", phonetic: "/ɪɡˈzem.plɪ.faɪ/" },
    { word: "exert", meaning: "mengerahkan", type: "verb", phonetic: "/ɪɡˈzɜːrt/" },
    { word: "exploit", meaning: "memanfaatkan/mengeksploitasi", type: "verb", phonetic: "/ɪkˈsplɔɪt/" },
    { word: "fluctuate", meaning: "berfluktuasi", type: "verb", phonetic: "/ˈflʌk.tʃu.eɪt/" },
    { word: "foster", meaning: "mendorong/mengasuh", type: "verb", phonetic: "/ˈfɒs.tər/" },
    { word: "hinder", meaning: "menghalangi", type: "verb", phonetic: "/ˈhɪn.dər/" },
    { word: "hypothesize", meaning: "berhipotesis", type: "verb", phonetic: "/haɪˈpɒθ.ə.saɪz/" },
    { word: "implement", meaning: "melaksanakan", type: "verb", phonetic: "/ˈɪm.plɪ.ment/" },
    { word: "incorporate", meaning: "menggabungkan", type: "verb", phonetic: "/ɪnˈkɔːr.pər.eɪt/" },
    { word: "induce", meaning: "menyebabkan/merangsang", type: "verb", phonetic: "/ɪnˈdjuːs/" },
    { word: "inhibit", meaning: "menghambat", type: "verb", phonetic: "/ɪnˈhɪb.ɪt/" },
    { word: "initiate", meaning: "memprakarsai", type: "verb", phonetic: "/ɪˈnɪʃ.i.eɪt/" },
    { word: "innovate", meaning: "berinovasi", type: "verb", phonetic: "/ˈɪn.ə.veɪt/" },
    { word: "intervene", meaning: "campur tangan", type: "verb", phonetic: "/ˌɪn.təˈviːn/" },
    { word: "justify", meaning: "membenarkan", type: "verb", phonetic: "/ˈdʒʌs.tɪ.faɪ/" },
    { word: "liberate", meaning: "membebaskan", type: "verb", phonetic: "/ˈlɪb.ər.eɪt/" },
    { word: "liquidate", meaning: "melikuidasi", type: "verb", phonetic: "/ˈlɪk.wɪ.deɪt/" },
    { word: "manifest", meaning: "memanifestasikan", type: "verb", phonetic: "/ˈmæn.ɪ.fest/" },
    { word: "mitigate", meaning: "memitigasi/meredakan", type: "verb", phonetic: "/ˈmɪt.ɪ.ɡeɪt/" },
    { word: "necessitate", meaning: "mengharuskan", type: "verb", phonetic: "/nəˈses.ɪ.teɪt/" },
    { word: "nurture", meaning: "memelihara", type: "verb", phonetic: "/ˈnɜː.tʃər/" },
    { word: "obliterate", meaning: "melenyapkan", type: "verb", phonetic: "/əˈblɪt.ər.eɪt/" },
    { word: "obscure", meaning: "mengaburkan", type: "verb", phonetic: "/əbˈskjʊər/" },
    { word: "oversee", meaning: "mengawasi", type: "verb", phonetic: "/ˌoʊ.vərˈsiː/" },
    { word: "penetrate", meaning: "menembus", type: "verb", phonetic: "/ˈpen.ɪ.treɪt/" },
    { word: "perpetuate", meaning: "melestarikan (hal buruk)", type: "verb", phonetic: "/pəˈpetʃ.u.eɪt/" },
    { word: "perplex", meaning: "membingungkan", type: "verb", phonetic: "/pəˈpleks/" },
    { word: "ponder", meaning: "merenungkan", type: "verb", phonetic: "/ˈpɒn.dər/" },
    { word: "postulate", meaning: "mengasumsikan", type: "verb", phonetic: "/ˈpɒs.tʃə.leɪt/" },
    { word: "preclude", meaning: "menghalangi/mencegah", type: "verb", phonetic: "/prɪˈkluːd/" },
    { word: "prescribe", meaning: "meresepkan/menentukan", type: "verb", phonetic: "/prɪˈskraɪb/" },
    { word: "prevail", meaning: "menang/lazim", type: "verb", phonetic: "/prɪˈveɪl/" },
    { word: "prohibit", meaning: "melarang", type: "verb", phonetic: "/prəˈhɪb.ɪt/" },
    { word: "proliferate", meaning: "berkembang biak cepat", type: "verb", phonetic: "/prəˈlɪf.ər.eɪt/" },
    { word: "propagate", meaning: "menyebarkan", type: "verb", phonetic: "/ˈprɒp.ə.ɡeɪt/" },
    { word: "provoke", meaning: "memprovokasi", type: "verb", phonetic: "/prəˈvoʊk/" },
    { word: "ratify", meaning: "mengesahkan", type: "verb", phonetic: "/ˈræt.ɪ.faɪ/" },
    { word: "reconcile", meaning: "mendamaikan", type: "verb", phonetic: "/ˈrek.ən.saɪl/" },
    { word: "rectify", meaning: "memperbaiki/membenarkan", type: "verb", phonetic: "/ˈrek.tɪ.faɪ/" },
    { word: "refute", meaning: "membantah", type: "verb", phonetic: "/rɪˈfjuːt/" },
    { word: "reiterate", meaning: "mengulangi (penegasan)", type: "verb", phonetic: "/riˈɪt.ər.eɪt/" },
    { word: "relinquish", meaning: "melepaskan (hak/posisi)", type: "verb", phonetic: "/rɪˈlɪŋ.kwɪʃ/" },
    { word: "replicate", meaning: "mereplikasi", type: "verb", phonetic: "/ˈrep.lɪ.keɪt/" },
    { word: "repudiate", meaning: "menolak/tidak mengakui", type: "verb", phonetic: "/rɪˈpjuː.di.eɪt/" },
    { word: "resemble", meaning: "menyerupai", type: "verb", phonetic: "/rɪˈzem.bəl/" },
    { word: "resonate", meaning: "bergema/beresonansi", type: "verb", phonetic: "/ˈrez.ən.eɪt/" },
    { word: "restrain", meaning: "menahan diri", type: "verb", phonetic: "/rɪˈstreɪn/" },
    { word: "scrutinize", meaning: "meneliti dengan cermat", type: "verb", phonetic: "/ˈskruː.tɪ.naɪz/" },
    { word: "simulate", meaning: "mensimulasikan", type: "verb", phonetic: "/ˈsɪm.jə.leɪt/" },
    { word: "speculate", meaning: "berspekulasi", type: "verb", phonetic: "/ˈspek.jə.leɪt/" },
    { word: "stagnate", meaning: "mandek", type: "verb", phonetic: "/stæɡˈneɪt/" },
    { word: "stimulate", meaning: "merangsang", type: "verb", phonetic: "/ˈstɪm.jə.leɪt/" },
    { word: "stipulate", meaning: "menetapkan (syarat)", type: "verb", phonetic: "/ˈstɪp.jə.leɪt/" },
    { word: "subsidize", meaning: "mensubsidi", type: "verb", phonetic: "/ˈsʌb.sɪ.daɪz/" },
    { word: "substantiate", meaning: "membuktikan", type: "verb", phonetic: "/səbˈstæn.ʃi.eɪt/" },
    { word: "suppress", meaning: "menindas/menekan", type: "verb", phonetic: "/səˈpres/" },
    { word: "surpass", meaning: "melampaui", type: "verb", phonetic: "/səˈpɑːs/" },
    { word: "sustain", meaning: "menopang", type: "verb", phonetic: "/səˈsteɪn/" },
    { word: "transcend", meaning: "melampaui batas", type: "verb", phonetic: "/trænˈsend/" },
    { word: "underestimate", meaning: "meremehkan", type: "verb", phonetic: "/ˌʌn.dərˈes.tɪ.meɪt/" },
    { word: "underscore", meaning: "menggarisbawahi/menegaskan", type: "verb", phonetic: "/ˌʌn.dəˈskɔːr/" },
    { word: "undertake", meaning: "menjalankan/mengerjakan", type: "verb", phonetic: "/ˌʌn.dəˈteɪk/" },
    { word: "utilize", meaning: "memanfaatkan (formal)", type: "verb", phonetic: "/ˈjuː.tɪ.laɪz/" },
    { word: "validate", meaning: "mengesahkan", type: "verb", phonetic: "/ˈvæl.ɪ.deɪt/" },
    { word: "verify", meaning: "memverifikasi", type: "verb", phonetic: "/ˈver.ɪ.faɪ/" },
    { word: "yield", meaning: "menghasilkan/menyerah", type: "verb", phonetic: "/jiːld/" },

    // --- NOUNS / PHILOSOPHY / SOCIETY (130 Kata) ---
    { word: "abundance", meaning: "kelimpahan", type: "noun", phonetic: "/əˈbʌn.dəns/" },
    { word: "acquisition", meaning: "perolehan", type: "noun", phonetic: "/ˌæk.wɪˈzɪʃ.ən/" },
    { word: "advocacy", meaning: "advokasi", type: "noun", phonetic: "/ˈæd.və.kə.si/" },
    { word: "aesthetic", meaning: "estetika", type: "noun", phonetic: "/esˈθet.ɪk/" },
    { word: "affluence", meaning: "kekayaan/kemakmuran", type: "noun", phonetic: "/ˈæf.lu.əns/" },
    { word: "aggregation", meaning: "penggabungan", type: "noun", phonetic: "/ˌæɡ.rɪˈɡeɪ.ʃən/" },
    { word: "alienation", meaning: "keterasingan", type: "noun", phonetic: "/ˌeɪ.li.əˈneɪ.ʃən/" },
    { word: "allegiance", meaning: "kesetiaan", type: "noun", phonetic: "/əˈliː.dʒəns/" },
    { word: "ambiguity", meaning: "ambiguitas", type: "noun", phonetic: "/ˌæm.bɪˈɡjuː.ə.ti/" },
    { word: "analogy", meaning: "analogi", type: "noun", phonetic: "/əˈnæl.ə.dʒi/" },
    { word: "anomaly", meaning: "anomali/kejanggalan", type: "noun", phonetic: "/əˈnɒm.ə.li/" },
    { word: "antagonism", meaning: "antagonisme", type: "noun", phonetic: "/ænˈtæɡ.ə.nɪ.zəm/" },
    { word: "autonomy", meaning: "otonomi", type: "noun", phonetic: "/ɔːˈtɒn.ə.mi/" },
    { word: "benevolence", meaning: "kebajikan", type: "noun", phonetic: "/bəˈnev.əl.əns/" },
    { word: "bias", meaning: "bias/prasangka", type: "noun", phonetic: "/ˈbaɪ.əs/" },
    { word: "bureaucracy", meaning: "birokrasi", type: "noun", phonetic: "/bjʊəˈrɒk.rə.si/" },
    { word: "catalyst", meaning: "katalis/pemicu", type: "noun", phonetic: "/ˈkæt.əl.ɪst/" },
    { word: "chaos", meaning: "kekacauan", type: "noun", phonetic: "/ˈkeɪ.ɒs/" },
    { word: "chronology", meaning: "kronologi", type: "noun", phonetic: "/krəˈnɒl.ə.dʒi/" },
    { word: "coalition", meaning: "koalisi", type: "noun", phonetic: "/ˌkoʊ.əˈlɪʃ.ən/" },
    { word: "cohesion", meaning: "kohesi/kepaduan", type: "noun", phonetic: "/koʊˈhiː.ʒən/" },
    { word: "compliance", meaning: "kepatuhan", type: "noun", phonetic: "/kəmˈplaɪ.əns/" },
    { word: "conundrum", meaning: "teka-teki sulit", type: "noun", phonetic: "/kəˈnʌn.drəm/" },
    { word: "correlation", meaning: "korelasi", type: "noun", phonetic: "/ˌkɒr.əˈleɪ.ʃən/" },
    { word: "curriculum", meaning: "kurikulum", type: "noun", phonetic: "/kəˈrɪk.jə.ləm/" },
    { word: "cynicism", meaning: "sinisme", type: "noun", phonetic: "/ˈsɪn.ɪ.sɪ.zəm/" },
    { word: "dearth", meaning: "kelangkaan", type: "noun", phonetic: "/dɜːθ/" },
    { word: "decorum", meaning: "kesantunan", type: "noun", phonetic: "/dɪˈkɔː.rəm/" },
    { word: "deficit", meaning: "defisit", type: "noun", phonetic: "/ˈdef.ɪ.sɪt/" },
    { word: "demographics", meaning: "demografi", type: "noun", phonetic: "/ˌdem.əˈɡræf.ɪks/" },
    { word: "dichotomy", meaning: "dikotomi", type: "noun", phonetic: "/daɪˈkɒt.ə.mi/" },
    { word: "discourse", meaning: "wacana", type: "noun", phonetic: "/ˈdɪs.kɔːrs/" },
    { word: "discrepancy", meaning: "ketidaksesuaian", type: "noun", phonetic: "/dɪˈskrep.ən.si/" },
    { word: "diversity", meaning: "keragaman", type: "noun", phonetic: "/daɪˈvɜː.sə.ti/" },
    { word: "doctrine", meaning: "doktrin", type: "noun", phonetic: "/ˈdɒk.trɪn/" },
    { word: "efficacy", meaning: "kemanjuran", type: "noun", phonetic: "/ˈef.ɪ.kə.si/" },
    { word: "elitism", meaning: "elitisme", type: "noun", phonetic: "/iˈliː.tɪ.zəm/" },
    { word: "eloquence", meaning: "kefasihan bicara", type: "noun", phonetic: "/ˈel.ə.kwəns/" },
    { word: "empathy", meaning: "empati", type: "noun", phonetic: "/ˈem.pə.θi/" },
    { word: "enigma", meaning: "teka-teki", type: "noun", phonetic: "/əˈnɪɡ.mə/" },
    { word: "equilibrium", meaning: "keseimbangan", type: "noun", phonetic: "/ˌiː.kwɪˈlɪb.ri.əm/" },
    { word: "ethics", meaning: "etika", type: "noun", phonetic: "/ˈeθ.ɪks/" },
    { word: "euphemism", meaning: "eufemisme", type: "noun", phonetic: "/ˈjuː.fə.mɪ.zəm/" },
    { word: "evolution", meaning: "evolusi", type: "noun", phonetic: "/ˌiː.vəˈluː.ʃən/" },
    { word: "fallacy", meaning: "kekeliruan berpikir", type: "noun", phonetic: "/ˈfæl.ə.si/" },
    { word: "feasibility", meaning: "kelayakan", type: "noun", phonetic: "/ˌfiː.zəˈbɪl.ə.ti/" },
    { word: "fidelity", meaning: "kesetiaan/akurasi", type: "noun", phonetic: "/fɪˈdel.ə.ti/" },
    { word: "fluctuation", meaning: "fluktuasi", type: "noun", phonetic: "/ˌflʌk.tʃuˈeɪ.ʃən/" },
    { word: "paradigm", meaning: "paradigma", type: "noun", phonetic: "/ˈpær.ə.daɪm/" },
    { word: "paradox", meaning: "paradoks", type: "noun", phonetic: "/ˈpær.ə.dɒks/" },
    { word: "pragmatism", meaning: "pragmatisme", type: "noun", phonetic: "/ˈpræɡ.mə.tɪ.zəm/" },
    { word: "prestige", meaning: "gengsi/prestise", type: "noun", phonetic: "/presˈtiːʒ/" },
    { word: "prevalence", meaning: "prevalensi/kelaziman", type: "noun", phonetic: "/ˈprev.əl.əns/" },
    { word: "profound", meaning: "mendalam", type: "noun", phonetic: "/prəˈfaʊnd/" },
    { word: "propensity", meaning: "kecenderungan", type: "noun", phonetic: "/prəˈpen.sə.ti/" },
    { word: "prosperity", meaning: "kemakmuran", type: "noun", phonetic: "/prɒsˈper.ə.ti/" },
    { word: "protocol", meaning: "protokol", type: "noun", phonetic: "/ˈproʊ.tə.kɒl/" },
    { word: "prudence", meaning: "kebijaksanaan/kehati-hatian", type: "noun", phonetic: "/ˈpruː.dəns/" },
    { word: "ramification", meaning: "konsekuensi/percabangan", type: "noun", phonetic: "/ˌræm.ɪ.fɪˈkeɪ.ʃən/" },
    { word: "rationale", meaning: "dasar pemikiran", type: "noun", phonetic: "/ˌræʃ.əˈnɑːl/" },
    { word: "reciprocity", meaning: "timbal balik", type: "noun", phonetic: "/ˌres.ɪˈprɒs.ə.ti/" },
    { word: "redundancy", meaning: "kelebihan/redundansi", type: "noun", phonetic: "/rɪˈdʌn.dən.si/" },
    { word: "refinement", meaning: "pemurnian/perbaikan", type: "noun", phonetic: "/rɪˈfaɪn.mənt/" },
    { word: "regime", meaning: "rezim", type: "noun", phonetic: "/reɪˈʒiːm/" },
    { word: "relevance", meaning: "relevansi", type: "noun", phonetic: "/ˈrel.ə.vəns/" },
    { word: "resilience", meaning: "ketangguhan", type: "noun", phonetic: "/rɪˈzɪl.jəns/" },
    { word: "rhetoric", meaning: "retorika", type: "noun", phonetic: "/ˈret.ər.ɪk/" },
    { word: "sanction", meaning: "sanksi", type: "noun", phonetic: "/ˈsæŋk.ʃən/" },
    { word: "scarcity", meaning: "kelangkaan", type: "noun", phonetic: "/ˈskeə.sə.ti/" },
    { word: "scrutiny", meaning: "pemeriksaan cermat", type: "noun", phonetic: "/ˈskruː.tɪ.ni/" },
    { word: "secularism", meaning: "sekularisme", type: "noun", phonetic: "/ˈsek.jə.lə.rɪ.zəm/" },
    { word: "semantics", meaning: "semantik/makna", type: "noun", phonetic: "/sɪˈmæn.tɪks/" },
    { word: "sovereignty", meaning: "kedaulatan", type: "noun", phonetic: "/ˈsɒv.rən.ti/" },
    { word: "stature", meaning: "perawakan/reputasi", type: "noun", phonetic: "/ˈstætʃ.ər/" },
    { word: "stimulus", meaning: "stimulus", type: "noun", phonetic: "/ˈstɪm.jə.ləs/" },
    { word: "subsidy", meaning: "subsidi", type: "noun", phonetic: "/ˈsʌb.sɪ.di/" },
    { word: "superfluity", meaning: "kuberlebihan", type: "noun", phonetic: "/ˌsuː.pəˈfluː.ə.ti/" },
    { word: "synthesis", meaning: "sintesis", type: "noun", phonetic: "/ˈsɪn.θə.sɪs/" },
    { word: "tenacity", meaning: "kegigihan", type: "noun", phonetic: "/təˈnæs.ə.ti/" },
    { word: "terminology", meaning: "terminologi", type: "noun", phonetic: "/ˌtɜː.mɪˈnɒl.ə.dʒi/" },
    { word: "threshold", meaning: "ambang batas", type: "noun", phonetic: "/ˈθreʃ.hoʊld/" },
    { word: "tolerance", meaning: "toleransi", type: "noun", phonetic: "/ˈtɒl.ər.əns/" },
    { word: "trajectory", meaning: "lintasan", type: "noun", phonetic: "/trəˈdʒek.tər.i/" },
    { word: "transparency", meaning: "transparansi", type: "noun", phonetic: "/trænˈspær.ən.si/" },
    { word: "trauma", meaning: "trauma", type: "noun", phonetic: "/ˈtrɔː.mə/" },
    { word: "utility", meaning: "kegunaan", type: "noun", phonetic: "/juːˈtɪl.ə.ti/" },
    { word: "validity", meaning: "validitas", type: "noun", phonetic: "/vəˈlɪd.ə.ti/" },
    { word: "variable", meaning: "variabel", type: "noun", phonetic: "/ˈveə.ri.ə.bəl/" },
    { word: "vengeance", meaning: "balas dendam", type: "noun", phonetic: "/ˈven.dʒəns/" },
    { word: "versatility", meaning: "serbaguna", type: "noun", phonetic: "/ˌvɜː.səˈtɪl.ə.ti/" },
    { word: "viability", meaning: "kelayakan hidup", type: "noun", phonetic: "/ˌvaɪ.əˈbɪl.ə.ti/" },
    { word: "virtue", meaning: "kebajikan", type: "noun", phonetic: "/ˈvɜː.tʃuː/" },

    // --- ADJECTIVES (80 Kata) ---
    { word: "aesthetic", meaning: "estetik", type: "adjective", phonetic: "/esˈθet.ɪk/" },
    { word: "altruistic", meaning: "altruistik", type: "adjective", phonetic: "/ˌæl.truˈɪs.tɪk/" },
    { word: "ambivalent", meaning: "ambivalen/ragu", type: "adjective", phonetic: "/æmˈbɪv.ə.lənt/" },
    { word: "arbitrary", meaning: "sewenang-wenang", type: "adjective", phonetic: "/ˈɑː.bɪ.trer.i/" },
    { word: "austere", meaning: "sederhana/keras", type: "adjective", phonetic: "/ɔːˈstɪər/" },
    { word: "autonomous", meaning: "otonom", type: "adjective", phonetic: "/ɔːˈtɒn.ə.məs/" },
    { word: "cognitive", meaning: "kognitif", type: "adjective", phonetic: "/ˈkɒɡ.nɪ.tɪv/" },
    { word: "conclusive", meaning: "meyakinkan/final", type: "adjective", phonetic: "/kənˈkluː.sɪv/" },
    { word: "cumbersome", meaning: "merepotkan", type: "adjective", phonetic: "/ˈkʌm.bə.səm/" },
    { word: "cynical", meaning: "sinis", type: "adjective", phonetic: "/ˈsɪn.ɪ.kəl/" },
    { word: "didactic", meaning: "bersifat mendidik", type: "adjective", phonetic: "/daɪˈdæk.tɪk/" },
    { word: "diligent", meaning: "rajin", type: "adjective", phonetic: "/ˈdɪl.ɪ.dʒənt/" },
    { word: "discreet", meaning: "bijaksana/hati-hati", type: "adjective", phonetic: "/dɪˈskriːt/" },
    { word: "dogmatic", meaning: "dogmatis", type: "adjective", phonetic: "/dɒɡˈmæt.ɪk/" },
    { word: "eclectic", meaning: "eklektik/beragam", type: "adjective", phonetic: "/ekˈlek.tɪk/" },
    { word: "egregious", meaning: "sangat buruk", type: "adjective", phonetic: "/ɪˈɡriː.dʒəs/" },
    { word: "elusive", meaning: "sulit dipahami/dicapai", type: "adjective", phonetic: "/iˈluː.sɪv/" },
    { word: "empirical", meaning: "empiris", type: "adjective", phonetic: "/ɪmˈpɪr.ɪ.kəl/" },
    { word: "enigmatic", meaning: "teka-teki", type: "adjective", phonetic: "/ˌen.ɪɡˈmæt.ɪk/" },
    { word: "ephemeral", meaning: "fana/singkat", type: "adjective", phonetic: "/ɪˈfem.ər.əl/" },
    { word: "equivocal", meaning: "ambigu", type: "adjective", phonetic: "/ɪˈkwɪv.ə.kəl/" },
    { word: "esoteric", meaning: "esoteris/terbatas", type: "adjective", phonetic: "/ˌes.əˈter.ɪk/" },
    { word: "exemplary", meaning: "patut dicontoh", type: "adjective", phonetic: "/ɪɡˈzem.plər.i/" },
    { word: "exhaustive", meaning: "menyeluruh", type: "adjective", phonetic: "/ɪɡˈzɔː.stɪv/" },
    { word: "exotic", meaning: "eksotis", type: "adjective", phonetic: "/ɪɡˈzɒt.ɪk/" },
    { word: "extraneous", meaning: "asing/tidak relevan", type: "adjective", phonetic: "/ɪkˈstreɪ.ni.əs/" },
    { word: "fastidious", meaning: "rewel/teliti", type: "adjective", phonetic: "/fæsˈtɪd.i.əs/" },
    { word: "formidable", meaning: "tangguh/dahsyat", type: "adjective", phonetic: "/fɔːˈmɪd.ə.bəl/" },
    { word: "fortuitous", meaning: "kebetulan beruntung", type: "adjective", phonetic: "/fɔːˈtʃuː.ɪ.təs/" },
    { word: "frivolous", meaning: "sepele/main-main", type: "adjective", phonetic: "/ˈfrɪv.əl.əs/" },
    { word: "grandiose", meaning: "megah/muluk", type: "adjective", phonetic: "/ˈɡræn.di.oʊs/" },
    { word: "idiosyncratic", meaning: "unik/khas", type: "adjective", phonetic: "/ˌɪd.i.ə.sɪŋˈkræt.ɪk/" },
    { word: "immutable", meaning: "tidak berubah", type: "adjective", phonetic: "/ɪˈmjuː.tə.bəl/" },
    { word: "impartial", meaning: "tidak memihak", type: "adjective", phonetic: "/ɪmˈpɑːr.ʃəl/" },
    { word: "impetuous", meaning: "implusif", type: "adjective", phonetic: "/ɪmˈpetʃ.u.əs/" },
    { word: "implausible", meaning: "tidak masuk akal", type: "adjective", phonetic: "/ɪmˈplɔː.zə.bəl/" },
    { word: "inadvertent", meaning: "tidak sengaja", type: "adjective", phonetic: "/ˌɪn.ədˈvɜː.tənt/" },
    { word: "incisive", meaning: "tajam/tegas", type: "adjective", phonetic: "/ɪnˈsaɪ.sɪv/" },
    { word: "indigenous", meaning: "pribumi/asli", type: "adjective", phonetic: "/ɪnˈdɪdʒ.ɪ.nəs/" },
    { word: "indispensable", meaning: "sangat diperlukan", type: "adjective", phonetic: "/ˌɪn.dɪˈspen.sə.bəl/" },
    { word: "ineffable", meaning: "tak terlukiskan", type: "adjective", phonetic: "/ɪnˈef.ə.bəl/" },
    { word: "inherent", meaning: "melekat", type: "adjective", phonetic: "/ɪnˈher.ənt/" },
    { word: "innocuous", meaning: "tidak berbahaya", type: "adjective", phonetic: "/ɪˈnɒk.ju.əs/" },
    { word: "insatiable", meaning: "tak pernah puas", type: "adjective", phonetic: "/ɪnˈseɪ.ʃə.bəl/" },
    { word: "intangible", meaning: "tak berwujud", type: "adjective", phonetic: "/ɪnˈtæn.dʒə.bəl/" },
    { word: "intricate", meaning: "rumit", type: "adjective", phonetic: "/ˈɪn.trɪ.kət/" },
    { word: "intrinsic", meaning: "intrinsik", type: "adjective", phonetic: "/ɪnˈtrɪn.zɪk/" },
    { word: "invincible", meaning: "tak terkalahkan", type: "adjective", phonetic: "/ɪnˈvɪn.sə.bəl/" },
    { word: "judicious", meaning: "bijaksana", type: "adjective", phonetic: "/dʒuːˈdɪʃ.əs/" },
    { word: "laconic", meaning: "singkat/padat", type: "adjective", phonetic: "/ləˈkɒn.ɪk/" },
    { word: "lucid", meaning: "jelas/mudah dimengerti", type: "adjective", phonetic: "/ˈluː.sɪd/" },
    { word: "magnanimous", meaning: "murah hati", type: "adjective", phonetic: "/mæɡˈnæn.ɪ.məs/" },
    { word: "meticulous", meaning: "sangat teliti", type: "adjective", phonetic: "/məˈtɪk.jə.ləs/" },
    { word: "mundane", meaning: "duniawi/biasa", type: "adjective", phonetic: "/mʌnˈdeɪn/" },
    { word: "nefarious", meaning: "jahat", type: "adjective", phonetic: "/nəˈfeə.ri.əs/" },
    { word: "negligible", meaning: "bisa diabaikan", type: "adjective", phonetic: "/ˈneɡ.lɪ.dʒə.bəl/" },
    { word: "obsolete", meaning: "usang", type: "adjective", phonetic: "/ˌɒb.səˈliːt/" },
    { word: "omnipotent", meaning: "mahakuasa", type: "adjective", phonetic: "/ɒmˈnɪp.ə.tənt/" },
    { word: "ostentatious", meaning: "pamer", type: "adjective", phonetic: "/ˌɒs.tenˈteɪ.ʃəs/" },
    { word: "parsimonious", meaning: "pelit", type: "adjective", phonetic: "/ˌpɑː.sɪˈmoʊ.ni.əs/" },
    { word: "pervasive", meaning: "meresap/luas", type: "adjective", phonetic: "/pəˈveɪ.sɪv/" },
    { word: "plausible", meaning: "masuk akal", type: "adjective", phonetic: "/ˈplɔː.zə.bəl/" },
    { word: "precarious", meaning: "berbahaya/tidak stabil", type: "adjective", phonetic: "/prɪˈkeə.ri.əs/" },
    { word: "prolific", meaning: "produktif", type: "adjective", phonetic: "/prəˈlɪf.ɪk/" },
    { word: "quixotic", meaning: "terlalu idealis", type: "adjective", phonetic: "/kwɪkˈsɒt.ɪk/" },
    { word: "redundant", meaning: "redundan", type: "adjective", phonetic: "/rɪˈdʌn.dənt/" },
    { word: "resilient", meaning: "tangguh", type: "adjective", phonetic: "/rɪˈzɪl.jənt/" },
    { word: "reticent", meaning: "pendiam", type: "adjective", phonetic: "/ˈret.ɪ.sənt/" },
    { word: "robust", meaning: "kuat", type: "adjective", phonetic: "/roʊˈbʌst/" },
    { word: "scrupulous", meaning: "teliti/jujur", type: "adjective", phonetic: "/ˈskruː.pjə.ləs/" },
    { word: "spurious", meaning: "palsu", type: "adjective", phonetic: "/ˈspjʊə.ri.əs/" },
    { word: "stringent", meaning: "ketat/keras", type: "adjective", phonetic: "/ˈstrɪn.dʒənt/" },
    { word: "sublime", meaning: "luhur/agung", type: "adjective", phonetic: "/səˈblaɪm/" },
    { word: "tacit", meaning: "tersirat", type: "adjective", phonetic: "/ˈtæs.ɪt/" },
    { word: "tenuous", meaning: "lemah/tipis", type: "adjective", phonetic: "/ˈten.ju.əs/" },
    { word: "ubiquitous", meaning: "ada di mana-mana", type: "adjective", phonetic: "/juːˈbɪk.wɪ.təs/" },
    { word: "venerable", meaning: "terhormat", type: "adjective", phonetic: "/ˈven.ər.ə.bəl/" },
    { word: "vicarious", meaning: "seolah mengalami sendiri", type: "adjective", phonetic: "/vɪˈkeə.ri.əs/" },
    { word: "volatile", meaning: "mudah berubah", type: "adjective", phonetic: "/ˈvɒl.ə.taɪl/" },
    { word: "zealous", meaning: "sangat antusias", type: "adjective", phonetic: "/ˈzel.əs/" }
];