/**
 * LINGUAQUEST - VOCABULARY BANK LEVEL 4 (300 WORDS)
 * Kategori: Mahir Dasar (Technical, Specific Conditions, Subtle Nuances)
 */

window.VOCAB_MASTER = window.VOCAB_MASTER || {};

window.VOCAB_MASTER.LV4 = [
    // --- ACTIONS / VERBS (90 Kata) ---
    { word: "abandon", meaning: "meninggalkan/meninggalkan tugas", type: "verb", phonetic: "/əˈbæn.dən/" },
    { word: "accumulate", meaning: "mengumpulkan/terkumpul", type: "verb", phonetic: "/əˈkjuː.mju.leɪt/" },
    { word: "acquire", meaning: "memperoleh", type: "verb", phonetic: "/əˈkwaɪər/" },
    { word: "adjust", meaning: "menyesuaikan", type: "verb", phonetic: "/əˈdʒʌst/" },
    { word: "alter", meaning: "mengubah", type: "verb", phonetic: "/ˈɒl.tər/" },
    { word: "anticipate", meaning: "mengantisipasi", type: "verb", phonetic: "/ænˈtɪs.ɪ.peɪt/" },
    { word: "assemble", meaning: "merakit/berkumpul", type: "verb", phonetic: "/əˈsem.bəl/" },
    { word: "assess", meaning: "menilai", type: "verb", phonetic: "/əˈses/" },
    { word: "assist", meaning: "membantu (formal)", type: "verb", phonetic: "/əˈsɪst/" },
    { word: "assume", meaning: "berasumsi", type: "verb", phonetic: "/əˈsjuːm/" },
    { word: "attempt", meaning: "mencoba (berusaha)", type: "verb", phonetic: "/əˈtempt/" },
    { word: "calculate", meaning: "menghitung", type: "verb", phonetic: "/ˈkæl.kju.leɪt/" },
    { word: "challenge", meaning: "menantang", type: "verb", phonetic: "/ˈtʃæl.ɪndʒ/" },
    { word: "clarify", meaning: "mengklarifikasi", type: "verb", phonetic: "/ˈklær.ɪ.faɪ/" },
    { word: "collapse", meaning: "runtuh", type: "verb", phonetic: "/kəˈlæps/" },
    { word: "combine", meaning: "menggabungkan", type: "verb", phonetic: "/kəmˈbaɪn/" },
    { word: "commit", meaning: "berkomitmen/melakukan", type: "verb", phonetic: "/kəˈmɪt/" },
    { word: "compensate", meaning: "mengimbangi/memberi kompensasi", type: "verb", phonetic: "/ˈkɒm.pən.seɪt/" },
    { word: "complicate", meaning: "merumitkan", type: "verb", phonetic: "/ˈkɒm.plɪ.keɪt/" },
    { word: "compose", meaning: "menyusun", type: "verb", phonetic: "/kəmˈpoʊz/" },
    { word: "conclude", meaning: "menyimpulkan", type: "verb", phonetic: "/kənˈkluːd/" },
    { word: "conduct", meaning: "mengadakan/melakukan", type: "verb", phonetic: "/kənˈdʌkt/" },
    { word: "consume", meaning: "mengonsumsi", type: "verb", phonetic: "/kənˈsjuːm/" },
    { word: "contribute", meaning: "berkontribusi", type: "verb", phonetic: "/kənˈtrɪb.juː/" },
    { word: "convert", meaning: "mengubah (bentuk/fungsi)", type: "verb", phonetic: "/kənˈvɜːrt/" },
    { word: "convey", meaning: "menyampaikan", type: "verb", phonetic: "/kənˈveɪ/" },
    { word: "cooperate", meaning: "bekerja sama", type: "verb", phonetic: "/koʊˈɒp.ər.eɪt/" },
    { word: "critique", meaning: "mengkritik", type: "verb", phonetic: "/krɪˈtiːk/" },
    { word: "demonstrate", meaning: "mendemonstrasikan", type: "verb", phonetic: "/ˈdem.ən.streɪt/" },
    { word: "derive", meaning: "berasal dari/memperoleh", type: "verb", phonetic: "/dɪˈraɪv/" },
    { word: "detect", meaning: "mendeteksi", type: "verb", phonetic: "/dɪˈtekt/" },
    { word: "distribute", meaning: "mendistribusikan", type: "verb", phonetic: "/dɪˈstrɪb.juː/" },
    { word: "eliminate", meaning: "mengeliminasi/menghapus", type: "verb", phonetic: "/iˈlɪm.ɪ.neɪt/" },
    { word: "emphasize", meaning: "menekankan", type: "verb", phonetic: "/ˈem.fə.saɪz/" },
    { word: "encounter", meaning: "menghadapi/bertemu", type: "verb", phonetic: "/ɪnˈkaʊn.tər/" },
    { word: "ensure", meaning: "memastikan", type: "verb", phonetic: "/ɪnˈʃɔːr/" },
    { word: "establish", meaning: "mendirikan/menetapkan", type: "verb", phonetic: "/ɪˈstæb.lɪʃ/" },
    { word: "evaluate", meaning: "mengevaluasi", type: "verb", phonetic: "/ɪˈvæl.ju.eɪt/" },
    { word: "expand", meaning: "memperluas", type: "verb", phonetic: "/ɪkˈspænd/" },
    { word: "facilitate", meaning: "memfasilitasi", type: "verb", phonetic: "/fəˈsɪl.ɪ.teɪt/" },
    { word: "generate", meaning: "menghasilkan", type: "verb", phonetic: "/ˈdʒen.ə.reɪt/" },
    { word: "guarantee", meaning: "menjamin", type: "verb", phonetic: "/ˌɡær.ənˈtiː/" },
    { word: "illustrate", meaning: "mengilustrasikan", type: "verb", phonetic: "/ˈɪl.ə.streɪt/" },
    { word: "implement", meaning: "melaksanakan", type: "verb", phonetic: "/ˈɪm.plɪ.ment/" },
    { word: "imply", meaning: "menyiratkan", type: "verb", phonetic: "/ɪmˈplaɪ/" },
    { word: "impose", meaning: "memaksakan", type: "verb", phonetic: "/ɪmˈpoʊz/" },
    { word: "incorporate", meaning: "menggabungkan", type: "verb", phonetic: "/ɪnˈkɔːr.pər.eɪt/" },
    { word: "initiate", meaning: "memulai", type: "verb", phonetic: "/ɪˈnɪʃ.i.eɪt/" },
    { word: "insert", meaning: "memasukkan", type: "verb", phonetic: "/ɪnˈsɜːrt/" },
    { word: "inspect", meaning: "memeriksa", type: "verb", phonetic: "/ɪnˈspekt/" },
    { word: "install", meaning: "memasang", type: "verb", phonetic: "/ɪnˈstɔːl/" },
    { word: "interact", meaning: "berinteraksi", type: "verb", phonetic: "/ˌɪn.təˈrækt/" },
    { word: "interpret", meaning: "menafsirkan", type: "verb", phonetic: "/ɪnˈtɜː.prət/" },
    { word: "investigate", meaning: "menyelidiki", type: "verb", phonetic: "/ɪnˈves.tɪ.ɡeɪt/" },
    { word: "justify", meaning: "membenarkan", type: "verb", phonetic: "/ˈdʒʌs.tɪ.faɪ/" },
    { word: "launch", meaning: "meluncurkan", type: "verb", phonetic: "/lɔːntʃ/" },
    { word: "maintain", meaning: "memelihara", type: "verb", phonetic: "/meɪnˈteɪn/" },
    { word: "manipulate", meaning: "memanipulasi", type: "verb", phonetic: "/məˈnɪp.jə.leɪt/" },
    { word: "modify", meaning: "memodifikasi", type: "verb", phonetic: "/ˈmɒd.ɪ.faɪ/" },
    { word: "monitor", meaning: "memantau", type: "verb", phonetic: "/ˈmɒn.ɪ.tər/" },
    { word: "motivate", meaning: "memotivasi", type: "verb", phonetic: "/ˈmoʊ.tɪ.veɪt/" },
    { word: "negotiate", meaning: "bernegosiasi", type: "verb", phonetic: "/nəˈɡoʊ.ʃi.eɪt/" },
    { word: "obtain", meaning: "mendapatkan", type: "verb", phonetic: "/əbˈteɪn/" },
    { word: "oppose", meaning: "menentang", type: "verb", phonetic: "/əˈpoʊz/" },
    { word: "organize", meaning: "mengorganisir", type: "verb", phonetic: "/ˈɔːr.ɡən.aɪz/" },
    { word: "overcome", meaning: "mengatasi", type: "verb", phonetic: "/ˌoʊ.vərˈkʌm/" },
    { word: "participate", meaning: "berpartisipasi", type: "verb", phonetic: "/pɑːrˈtɪs.ɪ.peɪt/" },
    { word: "perceive", meaning: "merasakan/memahami", type: "verb", phonetic: "/pəˈsiːv/" },
    { word: "persist", meaning: "bertahan/gigih", type: "verb", phonetic: "/pəˈsɪst/" },
    { word: "postpone", meaning: "menunda", type: "verb", phonetic: "/poʊstˈpoʊn/" },
    { word: "prioritize", meaning: "memprioritaskan", type: "verb", phonetic: "/praɪˈɒr.ɪ.taɪz/" },
    { word: "proceed", meaning: "melanjutkan", type: "verb", phonetic: "/prəˈsiːd/" },
    { word: "publish", meaning: "menerbitkan", type: "verb", phonetic: "/ˈpʌb.lɪʃ/" },
    { word: "pursue", meaning: "mengejar", type: "verb", phonetic: "/pəˈsjuː/" },
    { word: "quote", meaning: "mengutip", type: "verb", phonetic: "/kwoʊt/" },
    { word: "react", meaning: "bereaksi", type: "verb", phonetic: "/riˈækt/" },
    { word: "reform", meaning: "mereformasi", type: "verb", phonetic: "/rɪˈfɔːrm/" },
    { word: "reject", meaning: "menolak", type: "verb", phonetic: "/rɪˈdʒekt/" },
    { word: "release", meaning: "melepaskan", type: "verb", phonetic: "/rɪˈliːs/" },
    { word: "rely", meaning: "mengandalkan", type: "verb", phonetic: "/rɪˈlaɪ/" },
    { word: "resolve", meaning: "menyelesaikan", type: "verb", phonetic: "/rɪˈzɒlv/" },
    { word: "respond", meaning: "menanggapi", type: "verb", phonetic: "/rɪˈspɒnd/" },
    { word: "restore", meaning: "memulihkan", type: "verb", phonetic: "/rɪˈstɔːr/" },
    { word: "retain", meaning: "menahan/menyimpan", type: "verb", phonetic: "/rɪˈteɪn/" },
    { word: "reveal", meaning: "mengungkapkan", type: "verb", phonetic: "/rɪˈviːl/" },
    { word: "specialize", meaning: "mengkhususkan diri", type: "verb", phonetic: "/ˈspeʃ.əl.aɪz/" },
    { word: "stimulate", meaning: "merangsang", type: "verb", phonetic: "/ˈstɪm.jə.leɪt/" },
    { word: "submit", meaning: "menyerahkan", type: "verb", phonetic: "/səbˈmɪt/" },
    { word: "sustain", meaning: "mempertahankan", type: "verb", phonetic: "/səˈsteɪn/" },
    { word: "transform", meaning: "mengubah bentuk", type: "verb", phonetic: "/trænsˈfɔːrm/" },

    // --- NOUNS / SYSTEMS / TOOLS (130 Kata) ---
    { word: "absence", meaning: "ketidakhadiran", type: "noun", phonetic: "/ˈæb.səns/" },
    { word: "access", meaning: "akses", type: "noun", phonetic: "/ˈæk.ses/" },
    { word: "accommodation", meaning: "akomodasi", type: "noun", phonetic: "/əˌkɒm.əˈdeɪ.ʃən/" },
    { word: "achievement", meaning: "pencapaian", type: "noun", phonetic: "/əˈtʃiːv.mənt/" },
    { word: "agent", meaning: "agen", type: "noun", phonetic: "/ˈeɪ.dʒənt/" },
    { word: "agriculture", meaning: "pertanian", type: "noun", phonetic: "/ˈæɡ.rɪ.kʌl.tʃər/" },
    { word: "ambition", meaning: "ambisi", type: "noun", phonetic: "/æmˈbɪʃ.ən/" },
    { word: "appliance", meaning: "peralatan rumah tangga", type: "noun", phonetic: "/əˈplaɪ.əns/" },
    { word: "architecture", meaning: "arsitektur", type: "noun", phonetic: "/ˈɑːr.kɪ.tek.tʃər/" },
    { word: "aspect", meaning: "aspek", type: "noun", phonetic: "/ˈæs.pekt/" },
    { word: "atmosphere", meaning: "atmosfer", type: "noun", phonetic: "/ˈæt.mə.sfɪər/" },
    { word: "authority", meaning: "otoritas", type: "noun", phonetic: "/ɔːˈθɒr.ə.ti/" },
    { word: "budget", meaning: "anggaran", type: "noun", phonetic: "/ˈbʌdʒ.ɪt/" },
    { word: "candidate", meaning: "kandidat", type: "noun", phonetic: "/ˈkæn.dɪ.dət/" },
    { word: "capacity", meaning: "kapasitas", type: "noun", phonetic: "/kəˈpæs.ə.ti/" },
    { word: "category", meaning: "kategori", type: "noun", phonetic: "/ˈkæt.ə.ɡri/" },
    { word: "circumstance", meaning: "keadaan", type: "noun", phonetic: "/ˈsɜː.kəm.stæns/" },
    { word: "climate", meaning: "iklim", type: "noun", phonetic: "/ˈklaɪ.mət/" },
    { word: "component", meaning: "komponen", type: "noun", phonetic: "/kəmˈpoʊ.nənt/" },
    { word: "concept", meaning: "konsep", type: "noun", phonetic: "/ˈkɒn.sept/" },
    { word: "conflict", meaning: "konflik", type: "noun", phonetic: "/ˈkɒn.flɪkt/" },
    { word: "consumer", meaning: "konsumen", type: "noun", phonetic: "/kənˈsjuː.mər/" },
    { word: "continent", meaning: "benua", type: "noun", phonetic: "/ˈkɒn.tɪ.nənt/" },
    { word: "contract", meaning: "kontrak", type: "noun", phonetic: "/ˈkɒn.trækt/" },
    { word: "core", meaning: "inti", type: "noun", phonetic: "/kɔːr/" },
    { word: "criteria", meaning: "kriteria", type: "noun", phonetic: "/kraɪˈtɪə.ri.ə/" },
    { word: "criticism", meaning: "kritik", type: "noun", phonetic: "/ˈkrɪt.ɪ.sɪ.zəm/" },
    { word: "data", meaning: "data", type: "noun", phonetic: "/ˈdeɪ.tə/" },
    { word: "debt", meaning: "hutang", type: "noun", phonetic: "/det/" },
    { word: "decade", meaning: "dekade", type: "noun", phonetic: "/ˈdek.eɪd/" },
    { word: "defect", meaning: "cacat/kekurangan", type: "noun", phonetic: "/ˈdiː.fekt/" },
    { word: "delivery", meaning: "pengiriman", type: "noun", phonetic: "/dɪˈlɪv.ər.i/" },
    { word: "demand", meaning: "permintaan", type: "noun", phonetic: "/dɪˈmænd/" },
    { word: "device", meaning: "perangkat", type: "noun", phonetic: "/dɪˈvaɪs/" },
    { word: "diagram", meaning: "diagram", type: "noun", phonetic: "/ˈdaɪ.ə.ɡræm/" },
    { word: "distinction", meaning: "perbedaan", type: "noun", phonetic: "/dɪˈstɪŋk.ʃən/" },
    { word: "document", meaning: "dokumen", type: "noun", phonetic: "/ˈdɒk.jə.mənt/" },
    { word: "domain", meaning: "ranah/domain", type: "noun", phonetic: "/doʊˈmeɪn/" },
    { word: "draft", meaning: "rancangan", type: "noun", phonetic: "/drɑːft/" },
    { word: "economy", meaning: "ekonomi", type: "noun", phonetic: "/iˈkɒn.ə.mi/" },
    { word: "element", meaning: "elemen", type: "noun", phonetic: "/ˈel.ɪ.mənt/" },
    { word: "energy", meaning: "energi", type: "noun", phonetic: "/ˈen.ə.dʒi/" },
    { word: "enterprise", meaning: "perusahaan/usaha", type: "noun", phonetic: "/ˈen.tə.praɪz/" },
    { word: "entity", meaning: "entitas", type: "noun", phonetic: "/ˈen.tɪ.ti/" },
    { word: "environment", meaning: "lingkungan", type: "noun", phonetic: "/ɪnˈvaɪ.rən.mənt/" },
    { word: "error", meaning: "kesalahan", type: "noun", phonetic: "/ˈer.ər/" },
    { word: "essay", meaning: "esai", type: "noun", phonetic: "/ˈes.eɪ/" },
    { word: "estimate", meaning: "perkiraan", type: "noun", phonetic: "/ˈes.tɪ.mət/" },
    { word: "executive", meaning: "eksekutif", type: "noun", phonetic: "/ɪɡˈzek.jə.tɪv/" },
    { word: "extension", meaning: "ekstensi", type: "noun", phonetic: "/ɪkˈsten.ʃən/" },
    { word: "facility", meaning: "fasilitas", type: "noun", phonetic: "/fəˈsɪl.ə.ti/" },
    { word: "factor", meaning: "faktor", type: "noun", phonetic: "/ˈfæk.tər/" },
    { word: "feature", meaning: "fitur", type: "noun", phonetic: "/ˈfiː.tʃər/" },
    { word: "formula", meaning: "rumus", type: "noun", phonetic: "/ˈfɔːr.mjə.lə/" },
    { word: "foundation", meaning: "pondasi", type: "noun", phonetic: "/faʊnˈdeɪ.ʃən/" },
    { word: "framework", meaning: "kerangka kerja", type: "noun", phonetic: "/ˈfreɪm.wɜːrk/" },
    { word: "function", meaning: "fungsi", type: "noun", phonetic: "/ˈfʌŋk.ʃən/" },
    { word: "gap", meaning: "celah", type: "noun", phonetic: "/ɡæp/" },
    { word: "grade", meaning: "tingkatan/nilai", type: "noun", phonetic: "/ɡreɪd/" },
    { word: "guarantee", meaning: "jaminan", type: "noun", phonetic: "/ˌɡær.ənˈtiː/" },
    { word: "hardware", meaning: "perangkat keras", type: "noun", phonetic: "/ˈhɑːrd.wer/" },
    { word: "impact", meaning: "dampak", type: "noun", phonetic: "/ˈɪm.pækt/" },
    { word: "index", meaning: "indeks", type: "noun", phonetic: "/ˈɪn.deks/" },
    { word: "indicator", meaning: "indikator", type: "noun", phonetic: "/ˈɪn.dɪ.keɪ.tər/" },
    { word: "infrastructure", meaning: "infrastruktur", type: "noun", phonetic: "/ˈɪn.frəˌstrʌk.tʃər/" },
    { word: "innovation", meaning: "inovasi", type: "noun", phonetic: "/ˌɪn.əˈveɪ.ʃən/" },
    { word: "instance", meaning: "contoh/kejadian", type: "noun", phonetic: "/ˈɪn.stəns/" },
    { word: "institute", meaning: "lembaga", type: "noun", phonetic: "/ˈɪn.stɪ.tjuːt/" },
    { word: "intelligence", meaning: "kecerdasan", type: "noun", phonetic: "/ɪnˈtel.ɪ.dʒəns/" },
    { word: "internal", meaning: "internal", type: "noun", phonetic: "/ɪnˈtɜː.nəl/" },
    { word: "interview", meaning: "wawancara", type: "noun", phonetic: "/ˈɪn.tə.vjuː/" },
    { word: "issue", meaning: "isu/masalah", type: "noun", phonetic: "/ˈɪʃ.uː/" },
    { word: "item", meaning: "item/barang", type: "noun", phonetic: "/ˈaɪ.təm/" },
    { word: "journal", meaning: "jurnal", type: "noun", phonetic: "/ˈdʒɜː.nəl/" },
    { word: "label", meaning: "label", type: "noun", phonetic: "/ˈleɪ.bəl/" },
    { word: "layer", meaning: "lapisan", type: "noun", phonetic: "/ˈleɪ.ər/" },
    { word: "logic", meaning: "logika", type: "noun", phonetic: "/ˈlɒdʒ.ɪk/" },
    { word: "maintenance", meaning: "pemeliharaan", type: "noun", phonetic: "/ˈmeɪn.tən.əns/" },
    { word: "margin", meaning: "margin", type: "noun", phonetic: "/ˈmɑːr.dʒɪn/" },
    { word: "mechanism", meaning: "mekanisme", type: "noun", phonetic: "/ˈmek.ə.nɪ.zəm/" },
    { word: "media", meaning: "media", type: "noun", phonetic: "/ˈmiː.di.ə/" },
    { word: "minority", meaning: "minoritas", type: "noun", phonetic: "/maɪˈnɒr.ə.ti/" },
    { word: "module", meaning: "modul", type: "noun", phonetic: "/ˈmɒdʒ.uːl/" },
    { word: "network", meaning: "jaringan", type: "noun", phonetic: "/ˈnet.wɜːrk/" },
    { word: "notion", meaning: "gagasan", type: "noun", phonetic: "/ˈnoʊ.ʃən/" },
    { word: "objective", meaning: "tujuan/objektif", type: "noun", phonetic: "/əbˈdʒek.tɪv/" },
    { word: "option", meaning: "pilihan", type: "noun", phonetic: "/ˈɒp.ʃən/" },
    { word: "output", meaning: "keluaran", type: "noun", phonetic: "/ˈaʊt.pʊt/" },
    { word: "overlap", meaning: "tumpang tindih", type: "noun", phonetic: "/ˌoʊ.vərˈlæp/" },
    { word: "panel", meaning: "panel", type: "noun", phonetic: "/ˈpæn.əl/" },
    { word: "parameter", meaning: "parameter", type: "noun", phonetic: "/pəˈræm.ɪ.tər/" },
    { word: "phase", meaning: "fase", type: "noun", phonetic: "/feɪz/" },
    { word: "platform", meaning: "platform", type: "noun", phonetic: "/ˈplæt.fɔːrm/" },
    { word: "policy", meaning: "kebijakan", type: "noun", phonetic: "/ˈpɒl.ə.si/" },
    { word: "portion", meaning: "bagian", type: "noun", phonetic: "/ˈpɔːr.ʃən/" },
    { word: "potential", meaning: "potensi", type: "noun", phonetic: "/pəˈten.ʃəl/" },
    { word: "precision", meaning: "presisi", type: "noun", phonetic: "/prɪˈsɪʒ.ən/" },
    { word: "principle", meaning: "prinsip", type: "noun", phonetic: "/ˈprɪn.sə.pəl/" },
    { word: "priority", meaning: "prioritas", type: "noun", phonetic: "/praɪˈɒr.ə.ti/" },
    { word: "profile", meaning: "profil", type: "noun", phonetic: "/ˈproʊ.faɪl/" },
    { word: "protocol", meaning: "protokol", type: "noun", phonetic: "/ˈproʊ.tə.kɒl/" },
    { word: "publication", meaning: "publikasi", type: "noun", phonetic: "/ˌpʌb.lɪˈkeɪ.ʃən/" },
    { word: "range", meaning: "jangkauan", type: "noun", phonetic: "/reɪndʒ/" },
    { word: "ratio", meaning: "rasio", type: "noun", phonetic: "/ˈreɪ.ʃi.oʊ/" },
    { word: "region", meaning: "wilayah", type: "noun", phonetic: "/ˈriː.dʒən/" },
    { word: "regulation", meaning: "regulasi", type: "noun", phonetic: "/ˌreɡ.jəˈleɪ.ʃən/" },
    { word: "reliability", meaning: "keandalan", type: "noun", phonetic: "/rɪˌlaɪ.əˈbɪl.ə.ti/" },
    { word: "resource", meaning: "sumber daya", type: "noun", phonetic: "/ˈriː.sɔːrs/" },
    { word: "response", meaning: "respon", type: "noun", phonetic: "/rɪˈspɒns/" },
    { word: "role", meaning: "peran", type: "noun", phonetic: "/roʊl/" },
    { word: "route", meaning: "rute", type: "noun", phonetic: "/ruːt/" },
    { word: "sector", meaning: "sektor", type: "noun", phonetic: "/ˈsek.tər/" },
    { word: "sequence", meaning: "urutan", type: "noun", phonetic: "/ˈsiː.kwəns/" },
    { word: "series", meaning: "seri", type: "noun", phonetic: "/ˈsɪə.riːz/" },
    { word: "shift", meaning: "pergeseran/giliran", type: "noun", phonetic: "/ʃɪft/" },
    { word: "signal", meaning: "sinyal", type: "noun", phonetic: "/ˈsɪɡ.nəl/" },
    { word: "source", meaning: "sumber", type: "noun", phonetic: "/sɔːrs/" },
    { word: "spectrum", meaning: "spektrum", type: "noun", phonetic: "/ˈspek.trəm/" },
    { word: "stability", meaning: "stabilitas", type: "noun", phonetic: "/stəˈbɪl.ə.ti/" },
    { word: "statistic", meaning: "statistik", type: "noun", phonetic: "/stəˈtɪs.tɪk/" },
    { word: "status", meaning: "status", type: "noun", phonetic: "/ˈsteɪ.təs/" },
    { word: "structure", meaning: "struktur", type: "noun", phonetic: "/ˈstrʌk.tʃər/" },
    { word: "summary", meaning: "ringkasan", type: "noun", phonetic: "/ˈsʌm.ər.i/" },
    { word: "survey", meaning: "survei", type: "noun", phonetic: "/ˈsɜː.veɪ/" },
    { word: "task", meaning: "tugas", type: "noun", phonetic: "/tɑːsk/" },
    { word: "theme", meaning: "tema", type: "noun", phonetic: "/θiːm/" },
    { word: "topic", meaning: "topik", type: "noun", phonetic: "/ˈtɒp.ɪk/" },
    { word: "trend", meaning: "tren", type: "noun", phonetic: "/trend/" },
    { word: "version", meaning: "versi", type: "noun", phonetic: "/ˈvɜː.ʒən/" },
    { word: "volume", meaning: "volume", type: "noun", phonetic: "/ˈvɒl.juːm/" },

    // --- ADJECTIVES (80 Kata) ---
    { word: "abstract", meaning: "abstrak", type: "adjective", phonetic: "/ˈæb.strækt/" },
    { word: "adequate", meaning: "memadai", type: "adjective", phonetic: "/ˈæd.ə.kwət/" },
    { word: "alternative", meaning: "alternatif", type: "adjective", phonetic: "/ɒlˈtɜː.nə.tɪv/" },
    { word: "ambiguous", meaning: "ambigu", type: "adjective", phonetic: "/æmˈbɪɡ.ju.əs/" },
    { word: "annual", meaning: "tahunan", type: "adjective", phonetic: "/ˈæn.ju.əl/" },
    { word: "apparent", meaning: "nyata/tampak", type: "adjective", phonetic: "/əˈpær.ənt/" },
    { word: "arbitrary", meaning: "sewenang-wenang/acak", type: "adjective", phonetic: "/ˈɑː.bɪ.trər.i/" },
    { word: "artificial", meaning: "buatan", type: "adjective", phonetic: "/ˌɑː.tɪˈfɪʃ.əl/" },
    { word: "automatic", meaning: "otomatis", type: "adjective", phonetic: "/ˌɔː.təˈmæt.ɪk/" },
    { word: "brief", meaning: "singkat", type: "adjective", phonetic: "/briːf/" },
    { word: "chemical", meaning: "kimia", type: "adjective", phonetic: "/ˈkem.ɪ.kəl/" },
    { word: "civil", meaning: "sipil", type: "adjective", phonetic: "/ˈsɪv.əl/" },
    { word: "classic", meaning: "klasik", type: "adjective", phonetic: "/ˈklæs.ɪk/" },
    { word: "coherent", meaning: "koheren/nyambung", type: "adjective", phonetic: "/koʊˈhɪə.rənt/" },
    { word: "comprehensive", meaning: "komprehensif/luas", type: "adjective", phonetic: "/ˌkɒm.prɪˈhen.sɪv/" },
    { word: "considerable", meaning: "cukup besar", type: "adjective", phonetic: "/kənˈsɪd.ər.ə.bəl/" },
    { word: "constant", meaning: "konstan", type: "adjective", phonetic: "/ˈkɒn.stənt/" },
    { word: "contemporary", meaning: "kontemporer", type: "adjective", phonetic: "/kənˈtem.pə.rer.i/" },
    { word: "contradictory", meaning: "kontradiktif", type: "adjective", phonetic: "/ˌkɒn.trəˈdɪk.tər.i/" },
    { word: "controversial", meaning: "kontroversial", type: "adjective", phonetic: "/ˌkɒn.trəˈvɜː.ʃəl/" },
    { word: "corporate", meaning: "perusahaan/korporat", type: "adjective", phonetic: "/ˈkɔː.pər.ət/" },
    { word: "crucial", meaning: "sangat penting", type: "adjective", phonetic: "/ˈkruː.ʃəl/" },
    { word: "diverse", meaning: "beragam", type: "adjective", phonetic: "/daɪˈvɜːrs/" },
    { word: "domestic", meaning: "domestik", type: "adjective", phonetic: "/dəˈmes.tɪk/" },
    { word: "dominant", meaning: "dominan", type: "adjective", phonetic: "/ˈdɒm.ɪ.nənt/" },
    { word: "dynamic", meaning: "dinamis", type: "adjective", phonetic: "/daɪˈnæm.ɪk/" },
    { word: "economic", meaning: "ekonomi", type: "adjective", phonetic: "/ˌiː.kəˈnɒm.ɪk/" },
    { word: "equivalent", meaning: "setara", type: "adjective", phonetic: "/ɪˈkwɪv.əl.ənt/" },
    { word: "ethical", meaning: "etis", type: "adjective", phonetic: "/ˈeθ.ɪ.kəl/" },
    { word: "explicit", meaning: "eksplisit/jelas", type: "adjective", phonetic: "/ɪkˈsplɪs.ɪt/" },
    { word: "external", meaning: "eksternal", type: "adjective", phonetic: "/ɪkˈstɜː.nəl/" },
    { word: "feasible", meaning: "layak", type: "adjective", phonetic: "/ˈfiː.zə.bəl/" },
    { word: "flexible", meaning: "fleksibel", type: "adjective", phonetic: "/ˈflek.sə.bəl/" },
    { word: "fundamental", meaning: "mendasar", type: "adjective", phonetic: "/ˌfʌn.dəˈmen.təl/" },
    { word: "guilty", meaning: "bersalah", type: "adjective", phonetic: "/ˈɡɪl.ti/" },
    { word: "identical", meaning: "identik", type: "adjective", phonetic: "/aɪˈden.tɪ.kəl/" },
    { word: "implicit", meaning: "tersirat", type: "adjective", phonetic: "/ɪmˈplɪs.ɪt/" },
    { word: "inevitable", meaning: "tak terelakkan", type: "adjective", phonetic: "/ɪnˈev.ɪ.tə.bəl/" },
    { word: "infinite", meaning: "tak terbatas", type: "adjective", phonetic: "/ˈɪn.fɪ.nət/" },
    { word: "inherent", meaning: "melekat", type: "adjective", phonetic: "/ɪnˈher.ənt/" },
    { word: "initial", meaning: "awal", type: "adjective", phonetic: "/ɪˈnɪʃ.əl/" },
    { word: "innovative", meaning: "inovatif", type: "adjective", phonetic: "/ˈɪn.ə.veɪ.tɪv/" },
    { word: "intense", meaning: "intens", type: "adjective", phonetic: "/ɪnˈtens/" },
    { word: "internal", meaning: "internal", type: "adjective", phonetic: "/ɪnˈtɜː.nəl/" },
    { word: "isolated", meaning: "terisolasi", type: "adjective", phonetic: "/ˈaɪ.sə.leɪ.tɪd/" },
    { word: "legal", meaning: "legal", type: "adjective", phonetic: "/ˈliː.ɡəl/" },
    { word: "liberal", meaning: "liberal", type: "adjective", phonetic: "/ˈlɪb.ər.əl/" },
    { word: "marginal", meaning: "marjinal", type: "adjective", phonetic: "/ˈmɑː.dʒɪ.nəl/" },
    { word: "maximum", meaning: "maksimum", type: "adjective", phonetic: "/ˈmæk.sɪ.məm/" },
    { word: "minimum", meaning: "minimum", type: "adjective", phonetic: "/ˈmɪn.ɪ.məm/" },
    { word: "mutual", meaning: "bersama", type: "adjective", phonetic: "/ˈmjuː.tʃu.əl/" },
    { word: "neutral", meaning: "netral", type: "adjective", phonetic: "/ˈnjuː.trəl/" },
    { word: "notable", meaning: "patut diperhatikan", type: "adjective", phonetic: "/ˈnoʊ.tə.bəl/" },
    { word: "obvious", meaning: "jelas", type: "adjective", phonetic: "/ˈɒb.vi.əs/" },
    { word: "optional", meaning: "opsional", type: "adjective", phonetic: "/ˈɒp.ʃən.əl/" },
    { word: "passive", meaning: "pasif", type: "adjective", phonetic: "/ˈpæs.ɪv/" },
    { word: "persistent", meaning: "gigih", type: "adjective", phonetic: "/pəˈsɪs.tənt/" },
    { word: "precise", meaning: "tepat/presisi", type: "adjective", phonetic: "/prɪˈsaɪs/" },
    { word: "primary", meaning: "primer/utama", type: "adjective", phonetic: "/ˈpraɪ.mer.i/" },
    { word: "prior", meaning: "sebelumnya", type: "adjective", phonetic: "/praɪər/" },
    { word: "radical", meaning: "radikal", type: "adjective", phonetic: "/ˈræd.ɪ.kəl/" },
    { word: "random", meaning: "acak", type: "adjective", phonetic: "/ˈræn.dəm/" },
    { word: "rational", meaning: "rasional", type: "adjective", phonetic: "/ˈræʃ.ən.əl/" },
    { word: "secure", meaning: "aman", type: "adjective", phonetic: "/sɪˈkjʊər/" },
    { word: "sole", meaning: "satu-satunya", type: "adjective", phonetic: "/soʊl/" },
    { word: "somewhat", meaning: "agak", type: "adjective", phonetic: "/ˈsʌm.wɒt/" },
    { word: "sophisticated", meaning: "canggih/berpengalaman", type: "adjective", phonetic: "/səˈfɪs.tɪ.keɪ.tɪd/" },
    { word: "stable", meaning: "stabil", type: "adjective", phonetic: "/ˈsteɪ.bəl/" },
    { word: "statistical", meaning: "statistik", type: "adjective", phonetic: "/stəˈtɪs.tɪ.kəl/" },
    { word: "subsequent", meaning: "berikutnya", type: "adjective", phonetic: "/ˈsʌb.sɪ.kwənt/" },
    { word: "substantial", meaning: "substansial", type: "adjective", phonetic: "/səbˈstæn.ʃəl/" },
    { word: "subtle", meaning: "halus/tidak kentara", type: "adjective", phonetic: "/ˈsʌt.əl/" },
    { word: "sufficient", meaning: "mencukupi", type: "adjective", phonetic: "/səˈfɪʃ.ənt/" },
    { word: "technical", meaning: "teknis", type: "adjective", phonetic: "/ˈtek.nɪ.kəl/" },
    { word: "terminal", meaning: "terminal/akhir", type: "adjective", phonetic: "/ˈtɜː.mɪ.nəl/" },
    { word: "underlying", meaning: "yang mendasari", type: "adjective", phonetic: "/ˌʌn.dəˈlaɪ.ɪŋ/" },
    { word: "valid", meaning: "valid", type: "adjective", phonetic: "/ˈvæl.ɪd/" },
    { word: "variable", meaning: "variabel", type: "adjective", phonetic: "/ˈveə.ri.ə.bəl/" },
    { word: "vast", meaning: "luas", type: "adjective", phonetic: "/vɑːst/" },
    { word: "virtual", meaning: "virtual", type: "adjective", phonetic: "/ˈvɜː.tʃu.əl/" }
];