/**
 * LINGUAQUEST - VOCABULARY BANK LEVEL 3 (300 WORDS)
 * Kategori: Menengah Tinggi (Communication, Emotions, Professional, Abstract Concepts)
 */

window.VOCAB_MASTER = window.VOCAB_MASTER || {};

window.VOCAB_MASTER.LV3 = [
    // --- ACTIONS / VERBS (90 Kata) ---
    { word: "achieve", meaning: "mencapai", type: "verb", phonetic: "/əˈtʃiːv/" },
    { word: "consider", meaning: "mempertimbangkan", type: "verb", phonetic: "/kənˈsɪd.ər/" },
    { word: "discuss", meaning: "mendiskusikan", type: "verb", phonetic: "/dɪˈskʌs/" },
    { word: "encourage", meaning: "menyemangati", type: "verb", phonetic: "/ɪnˈkʌr.ɪdʒ/" },
    { word: "imagine", meaning: "membayangkan", type: "verb", phonetic: "/ɪˈmædʒ.ɪn/" },
    { word: "improve", meaning: "meningkatkan", type: "verb", phonetic: "/ɪmˈpruːv/" },
    { word: "involve", meaning: "melibatkan", type: "verb", phonetic: "/ɪnˈvɒlv/" },
    { word: "organize", meaning: "mengatur", type: "verb", phonetic: "/ˈɔːr.ɡən.aɪz/" },
    { word: "participate", meaning: "berpartisipasi", type: "verb", phonetic: "/pɑːrˈtɪs.ɪ.peɪt/" },
    { word: "prevent", meaning: "mencegah", type: "verb", phonetic: "/prɪˈvent/" },
    { word: "produce", meaning: "menghasilkan", type: "verb", phonetic: "/prəˈduːs/" },
    { word: "provide", meaning: "menyediakan", type: "verb", phonetic: "/prəˈvaɪd/" },
    { word: "recognize", meaning: "mengenali", type: "verb", phonetic: "/ˈrek.əɡ.naɪz/" },
    { word: "recommend", meaning: "menyarankan", type: "verb", phonetic: "/ˌrek.əˈmend/" },
    { word: "reduce", meaning: "mengurangi", type: "verb", phonetic: "/rɪˈdʒuːs/" },
    { word: "reflect", meaning: "mencerminkan", type: "verb", phonetic: "/rɪˈflekt/" },
    { word: "require", meaning: "membutuhkan/mewajibkan", type: "verb", phonetic: "/rɪˈkwaɪər/" },
    { word: "suggest", meaning: "menyarankan", type: "verb", phonetic: "/səˈdʒest/" },
    { word: "support", meaning: "mendukung", type: "verb", phonetic: "/səˈpɔːrt/" },
    { word: "wonder", meaning: "bertanya-tanya", type: "verb", phonetic: "/ˈwʌn.dər/" },
    { word: "accept", meaning: "menerima", type: "verb", phonetic: "/əkˈsept/" },
    { word: "admit", meaning: "mengakui", type: "verb", phonetic: "/ədˈmɪt/" },
    { word: "affect", meaning: "mempengaruhi", type: "verb", phonetic: "/əˈfekt/" },
    { word: "announce", meaning: "mengumumkan", type: "verb", phonetic: "/əˈnaʊns/" },
    { word: "apply", meaning: "menerapkan/melamar", type: "verb", phonetic: "/əˈplaɪ/" },
    { word: "appreciate", meaning: "menghargai", type: "verb", phonetic: "/əˈpriː.ʃi.eɪt/" },
    { word: "argue", meaning: "berdebat", type: "verb", phonetic: "/ˈɑːr.ɡjuː/" },
    { word: "avoid", meaning: "menghindari", type: "verb", phonetic: "/əˈvɔɪd/" },
    { word: "cause", meaning: "menyebabkan", type: "verb", phonetic: "/kɔːz/" },
    { word: "challenge", meaning: "menantang", type: "verb", phonetic: "/ˈtʃæl.ɪndʒ/" },
    { word: "compare", meaning: "membandingkan", type: "verb", phonetic: "/kəmˈpeər/" },
    { word: "complain", meaning: "mengeluh", type: "verb", phonetic: "/kəmˈpleɪn/" },
    { word: "confirm", meaning: "mengonfirmasi", type: "verb", phonetic: "/kənˈfɜːrm/" },
    { word: "convince", meaning: "meyakinkan", type: "verb", phonetic: "/kənˈvɪns/" },
    { word: "describe", meaning: "mendeskripsikan", type: "verb", phonetic: "/dɪˈskraɪb/" },
    { word: "deserve", meaning: "pantas mendapatkan", type: "verb", phonetic: "/dɪˈzɜːrv/" },
    { word: "develop", meaning: "mengembangkan", type: "verb", phonetic: "/dɪˈvel.əp/" },
    { word: "disagree", meaning: "tidak setuju", type: "verb", phonetic: "/ˌdɪs.əˈɡriː/" },
    { word: "disturb", meaning: "mengganggu", type: "verb", phonetic: "/dɪˈstɜːrb/" },
    { word: "examine", meaning: "memeriksa", type: "verb", phonetic: "/ɪɡˈzæm.ɪn/" },
    { word: "exist", meaning: "ada/eksis", type: "verb", phonetic: "/ɪɡˈzɪst/" },
    { word: "expect", meaning: "mengharapkan", type: "verb", phonetic: "/ɪkˈspekt/" },
    { word: "experience", meaning: "mengalami", type: "verb", phonetic: "/ɪkˈspɪə.ri.əns/" },
    { word: "express", meaning: "mengungkapkan", type: "verb", phonetic: "/ɪkˈspres/" },
    { word: "focus", meaning: "fokus", type: "verb", phonetic: "/ˈfoʊ.kəs/" },
    { word: "handle", meaning: "menangani", type: "verb", phonetic: "/ˈhæn.dəl/" },
    { word: "identify", meaning: "mengidentifikasi", type: "verb", phonetic: "/aɪˈden.tɪ.faɪ/" },
    { word: "ignore", meaning: "mengabaikan", type: "verb", phonetic: "/ɪɡˈnɔːr/" },
    { word: "imagine", meaning: "berimajinasi", type: "verb", phonetic: "/ɪˈmædʒ.ɪn/" },
    { word: "include", meaning: "termasuk", type: "verb", phonetic: "/ɪnˈkluːd/" },
    { word: "indicate", meaning: "menunjukkan", type: "verb", phonetic: "/ˈɪn.dɪ.keɪt/" },
    { word: "influence", meaning: "mempengaruhi", type: "verb", phonetic: "/ˈɪn.flu.əns/" },
    { word: "intend", meaning: "berniat", type: "/ɪnˈtend/" },
    { word: "manage", meaning: "mengelola", type: "verb", phonetic: "/ˈmæn.ɪdʒ/" },
    { word: "mention", meaning: "menyebutkan", type: "verb", phonetic: "/ˈmen.ʃən/" },
    { word: "negotiate", meaning: "negosiasi", type: "verb", phonetic: "/nəˈɡoʊ.ʃi.eɪt/" },
    { word: "observe", meaning: "mengamati", type: "verb", phonetic: "/əbˈzɜːrv/" },
    { word: "obtain", meaning: "mendapatkan", type: "verb", phonetic: "/əbˈteɪn/" },
    { word: "occur", meaning: "terjadi", type: "verb", phonetic: "/əˈkɜːr/" },
    { word: "offer", meaning: "menawarkan", type: "verb", phonetic: "/ˈɒf.ər/" },
    { word: "operate", meaning: "mengoperasikan", type: "verb", phonetic: "/ˈɒp.ər.eɪt/" },
    { word: "persuade", meaning: "membujuk", type: "verb", phonetic: "/pəˈsweɪd/" },
    { word: "predict", meaning: "memprediksi", type: "verb", phonetic: "/prɪˈdɪkt/" },
    { word: "prepare", meaning: "mempersiapkan", type: "verb", phonetic: "/prɪˈpeər/" },
    { word: "promise", meaning: "berjanji", type: "verb", phonetic: "/ˈprɒm.ɪs/" },
    { word: "protect", meaning: "melindungi", type: "verb", phonetic: "/prəˈtekt/" },
    { word: "realize", meaning: "menyadari", type: "verb", phonetic: "/ˈriː.ə.laɪz/" },
    { word: "receive", meaning: "menerima", type: "verb", phonetic: "/rɪˈsiːv/" },
    { word: "regret", meaning: "menyesal", type: "verb", phonetic: "/rɪˈɡret/" },
    { word: "relax", meaning: "bersantai", type: "verb", phonetic: "/rɪˈlæks/" },
    { word: "remain", meaning: "tetap", type: "verb", phonetic: "/rɪˈmeɪn/" },
    { word: "remind", meaning: "mengingatkan", type: "verb", phonetic: "/rɪˈmaɪnd/" },
    { word: "replace", meaning: "mengganti", type: "verb", phonetic: "/rɪˈpleɪs/" },
    { word: "represent", meaning: "mewakili", type: "verb", phonetic: "/ˌrep.rɪˈzent/" },
    { word: "request", meaning: "meminta", type: "verb", phonetic: "/rɪˈkwest/" },
    { word: "respond", meaning: "menanggapi", type: "verb", phonetic: "/rɪˈspɒnd/" },
    { word: "satisfy", meaning: "memuaskan", type: "verb", phonetic: "/ˈsæt.ɪs.faɪ/" },
    { word: "select", meaning: "memilih", type: "verb", phonetic: "/sɪˈlekt/" },
    { word: "separate", meaning: "memisahkan", type: "verb", phonetic: "/ˈsep.ər.eɪt/" },
    { word: "solve", meaning: "memecahkan", type: "verb", phonetic: "/sɒlv/" },
    { word: "suffer", meaning: "menderita", type: "verb", phonetic: "/ˈsʌf.ər/" },
    { word: "survive", meaning: "bertahan hidup", type: "verb", phonetic: "/səˈvaɪv/" },
    { word: "trust", meaning: "mempercayai", type: "verb", phonetic: "/trʌst/" },
    { word: "upset", meaning: "membuat kesal", type: "verb", phonetic: "/ʌpˈset/" },
    { word: "value", meaning: "menghargai", type: "verb", phonetic: "/ˈvæl.juː/" },
    { word: "volunteer", meaning: "sukarela", type: "verb", phonetic: "/ˌvɒl.ənˈtɪər/" },
    { word: "warn", meaning: "memperingatkan", type: "verb", phonetic: "/wɔːrn/" },
    { word: "waste", meaning: "membuang-buang", type: "verb", phonetic: "/weɪst/" },
    { word: "wish", meaning: "berharap", type: "verb", phonetic: "/wɪʃ/" },
    { word: "worry", meaning: "khawatir", type: "verb", phonetic: "/ˈwʌr.i/" },

    // --- NOUNS / CONCEPTS (130 Kata) ---
    { word: "ability", meaning: "kemampuan", type: "noun", phonetic: "/əˈbɪl.ə.ti/" },
    { word: "advantage", meaning: "keuntungan", type: "noun", phonetic: "/ədˈvɑːn.tɪdʒ/" },
    { word: "agreement", meaning: "perjanjian", type: "noun", phonetic: "/əˈɡriː.mənt/" },
    { word: "analysis", meaning: "analisis", type: "noun", phonetic: "/əˈnæl.ə.sɪs/" },
    { word: "approach", meaning: "pendekatan", type: "noun", phonetic: "/əˈproʊtʃ/" },
    { word: "attention", meaning: "perhatian", type: "noun", phonetic: "/əˈten.ʃən/" },
    { word: "audience", meaning: "penonton/hadirin", type: "noun", phonetic: "/ˈɔː.di.əns/" },
    { word: "behavior", meaning: "perilaku", type: "noun", phonetic: "/bɪˈheɪ.vjər/" },
    { word: "benefit", meaning: "manfaat", type: "noun", phonetic: "/ˈben.ɪ.fɪt/" },
    { word: "category", meaning: "kategori", type: "noun", phonetic: "/ˈkæt.ə.ɡri/" },
    { word: "challenge", meaning: "tantangan", type: "noun", phonetic: "/ˈtʃæl.ɪndʒ/" },
    { word: "collection", meaning: "koleksi", type: "noun", phonetic: "/kəˈlek.ʃən/" },
    { word: "communication", meaning: "komunikasi", type: "noun", phonetic: "/kəˌmjuː.nɪˈkeɪ.ʃən/" },
    { word: "community", meaning: "komunitas", type: "noun", phonetic: "/kəˈmjuː.nə.ti/" },
    { word: "comparison", meaning: "perbandingan", type: "noun", phonetic: "/kəmˈpær.ɪ.sən/" },
    { word: "competition", meaning: "kompetisi", type: "noun", phonetic: "/ˌkɒm.pəˈtɪʃ.ən/" },
    { word: "confidence", meaning: "kepercayaan diri", type: "noun", phonetic: "/ˈkɒn.fɪ.dəns/" },
    { word: "connection", meaning: "koneksi", type: "noun", phonetic: "/kəˈnek.ʃən/" },
    { word: "consequence", meaning: "konsekuensi", type: "noun", phonetic: "/ˈkɒn.sɪ.kwəns/" },
    { word: "contribution", meaning: "kontribusi", type: "noun", phonetic: "/ˌkɒn.trɪˈbjuː.ʃən/" },
    { word: "creativity", meaning: "kreativitas", type: "noun", phonetic: "/ˌkriː.eɪˈtɪv.ə.ti/" },
    { word: "decision", meaning: "keputusan", type: "noun", phonetic: "/dɪˈsɪʒ.ən/" },
    { word: "definition", meaning: "definisi", type: "noun", phonetic: "/ˌdef.ɪˈnɪʃ.ən/" },
    { word: "department", meaning: "departemen", type: "noun", phonetic: "/dɪˈpɑːrt.mənt/" },
    { word: "description", meaning: "deskripsi", type: "noun", phonetic: "/dɪˈskrɪp.ʃən/" },
    { word: "difference", meaning: "perbedaan", type: "noun", phonetic: "/ˈdɪf.ər.əns/" },
    { word: "direction", meaning: "arah", type: "noun", phonetic: "/daɪˈrek.ʃən/" },
    { word: "discovery", meaning: "penemuan", type: "noun", phonetic: "/dɪˈskʌv.ər.i/" },
    { word: "discussion", meaning: "diskusi", type: "noun", phonetic: "/dɪˈskʌʃ.ən/" },
    { word: "education", meaning: "pendidikan", type: "noun", phonetic: "/ˌedʒ.ʊˈkeɪ.ʃən/" },
    { word: "effect", meaning: "efek", type: "noun", phonetic: "/ɪˈfekt/" },
    { word: "emotion", meaning: "emosi", type: "noun", phonetic: "/ɪˈmoʊ.ʃən/" },
    { word: "employment", meaning: "pekerjaan/ketenagakerjaan", type: "noun", phonetic: "/ɪmˈplɔɪ.mənt/" },
    { word: "environment", meaning: "lingkungan", type: "noun", phonetic: "/ɪnˈvaɪ.rən.mənt/" },
    { word: "evidence", meaning: "bukti", type: "noun", phonetic: "/ˈev.ɪ.dəns/" },
    { word: "explanation", meaning: "penjelasan", type: "noun", phonetic: "/ˌek.spləˈneɪ.ʃən/" },
    { word: "expression", meaning: "ungkapan", type: "noun", phonetic: "/ɪkˈspreʃ.ən/" },
    { word: "failure", meaning: "kegagalan", type: "noun", phonetic: "/ˈfeɪ.ljər/" },
    { word: "freedom", meaning: "kebebasan", type: "noun", phonetic: "/ˈfriː.dəm/" },
    { word: "generation", meaning: "generasi", type: "noun", phonetic: "/ˌdʒen.əˈreɪ.ʃən/" },
    { word: "goal", meaning: "tujuan", type: "noun", phonetic: "/ɡoʊl/" },
    { word: "growth", meaning: "pertumbuhan", type: "noun", phonetic: "/ɡroʊθ/" },
    { word: "guidance", meaning: "bimbingan", type: "noun", phonetic: "/ˈɡaɪ.dəns/" },
    { word: "health", meaning: "kesehatan", type: "noun", phonetic: "/helθ/" },
    { word: "honesty", meaning: "kejujuran", type: "noun", phonetic: "/ˈɒn.ə.sti/" },
    { word: "importance", meaning: "pentingnya", type: "noun", phonetic: "/ɪmˈpɔːr.təns/" },
    { word: "improvement", meaning: "peningkatan", type: "noun", phonetic: "/ɪmˈpruːv.mənt/" },
    { word: "information", meaning: "informasi", type: "noun", phonetic: "/ˌɪn.fəˈmeɪ.ʃən/" },
    { word: "innovation", meaning: "inovasi", type: "noun", phonetic: "/ˌɪn.əˈveɪ.ʃən/" },
    { word: "instruction", meaning: "instruksi", type: "noun", phonetic: "/ɪnˈstrʌk.ʃən/" },
    { word: "intelligence", meaning: "kecerdasan", type: "noun", phonetic: "/ɪnˈtel.ɪ.dʒəns/" },
    { word: "interaction", meaning: "interaksi", type: "noun", phonetic: "/ˌɪn.təˈræk.ʃən/" },
    { word: "investment", meaning: "investasi", type: "noun", phonetic: "/ɪnˈvest.mənt/" },
    { word: "judgment", meaning: "penilaian", type: "noun", phonetic: "/ˈdʒʌdʒ.mənt/" },
    { word: "justice", meaning: "keadilan", type: "noun", phonetic: "/ˈdʒʌs.tɪs/" },
    { word: "knowledge", meaning: "pengetahuan", type: "noun", phonetic: "/ˈnɒl.ɪdʒ/" },
    { word: "leadership", meaning: "kepemimpinan", type: "noun", phonetic: "/ˈliː.də.ʃɪp/" },
    { word: "location", meaning: "lokasi", type: "noun", phonetic: "/loʊˈkeɪ.ʃən/" },
    { word: "management", meaning: "manajemen", type: "noun", phonetic: "/ˈmæn.ɪdʒ.mənt/" },
    { word: "measurement", meaning: "pengukuran", type: "noun", phonetic: "/ˈmeʒ.ə.mənt/" },
    { word: "membership", meaning: "keanggotaan", type: "noun", phonetic: "/ˈmem.bə.ʃɪp/" },
    { word: "mention", meaning: "sebutan", type: "noun", phonetic: "/ˈmen.ʃən/" },
    { word: "method", meaning: "metode", type: "noun", phonetic: "/ˈmeθ.əd/" },
    { word: "motivation", meaning: "motivasi", type: "noun", phonetic: "/ˌmoʊ.tɪˈveɪ.ʃən/" },
    { word: "movement", meaning: "gerakan", type: "noun", phonetic: "/ˈmuːv.mənt/" },
    { word: "negotiation", meaning: "negosiasi", type: "noun", phonetic: "/nəˌɡoʊ.ʃiˈeɪ.ʃən/" },
    { word: "observation", meaning: "pengamatan", type: "noun", phonetic: "/ˌɒb.zəˈveɪ.ʃən/" },
    { word: "opportunity", meaning: "peluang", type: "noun", phonetic: "/ˌɒp.əˈtjuː.nə.ti/" },
    { word: "organization", meaning: "organisasi", type: "noun", phonetic: "/ˌɔːr.ɡən.aɪˈzeɪ.ʃən/" },
    { word: "outcome", meaning: "hasil", type: "noun", phonetic: "/ˈaʊt.kʌm/" },
    { word: "patience", meaning: "kesabaran", type: "noun", phonetic: "/ˈpeɪ.ʃəns/" },
    { word: "performance", meaning: "performa", type: "noun", phonetic: "/pəˈfɔːr.məns/" },
    { word: "permission", meaning: "izin", type: "noun", phonetic: "/pəˈmɪʃ.ən/" },
    { word: "perspective", meaning: "perspektif", type: "noun", phonetic: "/pəˈspek.tɪv/" },
    { word: "philosophy", meaning: "filsafat", type: "noun", phonetic: "/fɪˈlɒs.ə.fi/" },
    { word: "population", meaning: "populasi", type: "noun", phonetic: "/ˌpɒp.jəˈleɪ.ʃən/" },
    { word: "possibility", meaning: "kemungkinan", type: "noun", phonetic: "/ˌpɒs.əˈbɪl.ə.ti/" },
    { word: "preference", meaning: "preferensi", type: "noun", phonetic: "/ˈpref.ər.əns/" },
    { word: "preparation", meaning: "persiapan", type: "noun", phonetic: "/ˌprep.ərˈeɪ.ʃən/" },
    { word: "presence", meaning: "kehadiran", type: "noun", phonetic: "/ˈprez.əns/" },
    { word: "priority", meaning: "prioritas", type: "noun", phonetic: "/praɪˈɒr.ə.ti/" },
    { word: "procedure", meaning: "prosedur", type: "noun", phonetic: "/prəˈsiː.dʒər/" },
    { word: "process", meaning: "proses", type: "noun", phonetic: "/ˈproʊ.ses/" },
    { word: "profession", meaning: "profesi", type: "noun", phonetic: "/prəˈfeʃ.ən/" },
    { word: "promotion", meaning: "promosi", type: "noun", phonetic: "/prəˈmoʊ.ʃən/" },
    { word: "property", meaning: "properti/milik", type: "noun", phonetic: "/ˈprɒp.ə.ti/" },
    { word: "proposal", meaning: "proposal", type: "noun", phonetic: "/prəˈpoʊ.zəl/" },
    { word: "protection", meaning: "perlindungan", type: "noun", phonetic: "/prəˈtek.ʃən/" },
    { word: "psychology", meaning: "psikologi", type: "noun", phonetic: "/saɪˈkɒl.ə.dʒi/" },
    { word: "quality", meaning: "kualitas", type: "noun", phonetic: "/ˈkwɒl.ə.ti/" },
    { word: "reaction", meaning: "reaksi", type: "noun", phonetic: "/riˈæk.ʃən/" },
    { word: "reality", meaning: "realitas", type: "noun", phonetic: "/riˈæl.ə.ti/" },
    { word: "recommendation", meaning: "rekomendasi", type: "noun", phonetic: "/ˌrek.ə.menˈdeɪ.ʃən/" },
    { word: "relationship", meaning: "hubungan", type: "noun", phonetic: "/rɪˈleɪ.ʃən.ʃɪp/" },
    { word: "reputation", meaning: "reputasi", type: "noun", phonetic: "/ˌrep.jəˈteɪ.ʃən/" },
    { word: "requirement", meaning: "persyaratan", type: "noun", phonetic: "/rɪˈkwaɪə.mənt/" },
    { word: "research", meaning: "penelitian", type: "noun", phonetic: "/rɪˈsɜːrtʃ/" },
    { word: "respect", meaning: "rasa hormat", type: "noun", phonetic: "/rɪˈspekt/" },
    { word: "responsibility", meaning: "tanggung jawab", type: "noun", phonetic: "/rɪˌspɒn.səˈbɪl.ə.ti/" },
    { word: "safety", meaning: "keamanan", type: "noun", phonetic: "/ˈseɪf.ti/" },
    { word: "satisfaction", meaning: "kepuasan", type: "noun", phonetic: "/ˌsæt.ɪsˈfæk.ʃən/" },
    { word: "science", meaning: "sains", type: "noun", phonetic: "/ˈsaɪ.əns/" },
    { word: "security", meaning: "keamanan", type: "noun", phonetic: "/sɪˈkjʊə.rə.ti/" },
    { word: "selection", meaning: "seleksi", type: "noun", phonetic: "/sɪˈlek.ʃən/" },
    { word: "situation", meaning: "situasi", type: "noun", phonetic: "/ˌsɪtʃ.uˈeɪ.ʃən/" },
    { word: "society", meaning: "masyarakat", type: "noun", phonetic: "/səˈsaɪ.ə.ti/" },
    { word: "solution", meaning: "solusi", type: "noun", phonetic: "/səˈluː.ʃən/" },
    { word: "strategy", meaning: "strategi", type: "noun", phonetic: "/ˈstræt.ə.dʒi/" },
    { word: "strength", meaning: "kekuatan", type: "noun", phonetic: "/streŋθ/" },
    { word: "suggestion", meaning: "saran", type: "noun", phonetic: "/səˈdʒes.tʃən/" },
    { word: "surface", meaning: "permukaan", type: "noun", phonetic: "/ˈsɜː.fɪs/" },
    { word: "system", meaning: "sistem", type: "noun", phonetic: "/ˈsɪs.təm/" },
    { word: "talent", meaning: "bakat", type: "noun", phonetic: "/ˈtæl.ənt/" },
    { word: "target", meaning: "target", type: "noun", phonetic: "/ˈtɑːr.ɡɪt/" },
    { word: "technology", meaning: "teknologi", type: "noun", phonetic: "/tekˈnɒl.ə.dʒi/" },
    { word: "theory", meaning: "teori", type: "noun", phonetic: "/ˈθɪə.ri/" },
    { word: "thought", meaning: "pemikiran", type: "noun", phonetic: "/θɔːt/" },
    { word: "tradition", meaning: "tradisi", type: "noun", phonetic: "/trəˈdɪʃ.ən/" },
    { word: "training", meaning: "pelatihan", type: "noun", phonetic: "/ˈtreɪ.nɪŋ/" },
    { word: "transportation", meaning: "transportasi", type: "noun", phonetic: "/ˌtræn.spɔːˈteɪ.ʃən/" },
    { word: "truth", meaning: "kebenaran", type: "noun", phonetic: "/truːθ/" },
    { word: "understanding", meaning: "pemahaman", type: "noun", phonetic: "/ˌʌn.dəˈstæn.dɪŋ/" },
    { word: "unit", meaning: "unit", type: "noun", phonetic: "/ˈjuː.nɪt/" },
    { word: "variety", meaning: "variasi", type: "noun", phonetic: "/vəˈraɪ.ə.ti/" },
    { word: "version", meaning: "versi", type: "noun", phonetic: "/ˈvɜː.ʒən/" },
    { word: "vision", meaning: "visi", type: "noun", phonetic: "/ˈvɪʒ.ən/" },
    { word: "warning", meaning: "peringatan", type: "noun", phonetic: "/ˈwɔː.nɪŋ/" },
    { word: "wealth", meaning: "kekayaan", type: "noun", phonetic: "/welθ/" },
    { word: "winner", meaning: "pemenang", type: "noun", phonetic: "/ˈwɪn.ər/" },
    { word: "wisdom", meaning: "kebijaksanaan", type: "noun", phonetic: "/ˈwɪz.dəm/" },
    { word: "worker", meaning: "pekerja", type: "noun", phonetic: "/ˈwɜː.kər/" },

    // --- ADJECTIVES (80 Kata) ---
    { word: "accurate", meaning: "akurat", type: "adjective", phonetic: "/ˈæk.jə.rət/" },
    { word: "additional", meaning: "tambahan", type: "adjective", phonetic: "/əˈdɪʃ.ən.əl/" },
    { word: "anxious", meaning: "cemas", type: "adjective", phonetic: "/ˈæŋk.ʃəs/" },
    { word: "appropriate", meaning: "tepat/layak", type: "adjective", phonetic: "/əˈproʊ.pri.ət/" },
    { word: "automatic", meaning: "otomatis", type: "adjective", phonetic: "/ˌɔː.təˈmæt.ɪk/" },
    { word: "aware", meaning: "sadar/tahu", type: "adjective", phonetic: "/əˈweər/" },
    { word: "basic", meaning: "dasar", type: "adjective", phonetic: "/ˈbeɪ.sɪk/" },
    { word: "capable", meaning: "mampu", type: "adjective", phonetic: "/ˈkeɪ.pə.bəl/" },
    { word: "certain", meaning: "yakin/tertentu", type: "adjective", phonetic: "/ˈsɜː.tən/" },
    { word: "competitive", meaning: "kompetitif", type: "adjective", phonetic: "/kəmˈpet.ə.tɪv/" },
    { word: "complex", meaning: "kompleks", type: "adjective", phonetic: "/ˈkɒm.pleks/" },
    { word: "confident", meaning: "percaya diri", type: "adjective", phonetic: "/ˈkɒn.fɪ.dənt/" },
    { word: "conscious", meaning: "sadar", type: "adjective", phonetic: "/ˈkɒn.ʃəs/" },
    { word: "creative", meaning: "kreatif", type: "adjective", phonetic: "/kriˈeɪ.tɪv/" },
    { word: "critical", meaning: "kritis", type: "adjective", phonetic: "/ˈkrɪt.ɪ.kəl/" },
    { word: "cultural", meaning: "budaya", type: "adjective", phonetic: "/ˈkʌl.tʃər.əl/" },
    { word: "curious", meaning: "penasaran", type: "adjective", phonetic: "/ˈkjʊə.ri.əs/" },
    { word: "dependent", meaning: "tergantung", type: "adjective", phonetic: "/dɪˈpen.dənt/" },
    { word: "detailed", meaning: "terperinci", type: "adjective", phonetic: "/ˈdiː.teɪld/" },
    { word: "determined", meaning: "bertekad", type: "adjective", phonetic: "/dɪˈtɜː.mɪnd/" },
    { word: "digital", meaning: "digital", type: "adjective", phonetic: "/ˈdɪdʒ.ɪ.təl/" },
    { word: "dramatic", meaning: "dramatis", type: "adjective", phonetic: "/drəˈmæt.ɪk/" },
    { word: "efficient", meaning: "efisien", type: "adjective", phonetic: "/ɪˈfɪʃ.ənt/" },
    { word: "emotional", meaning: "emosional", type: "adjective", phonetic: "/ɪˈmoʊ.ʃən.əl/" },
    { word: "entire", meaning: "seluruh", type: "adjective", phonetic: "/ɪnˈtaɪər/" },
    { word: "essential", meaning: "esensial/penting", type: "adjective", phonetic: "/ɪˈsen.ʃəl/" },
    { word: "exact", meaning: "tepat/persis", type: "adjective", phonetic: "/ɪɡˈzækt/" },
    { word: "excellent", meaning: "sangat baik", type: "adjective", phonetic: "/ˈek.səl.ənt/" },
    { word: "existing", meaning: "yang ada", type: "adjective", phonetic: "/ɪɡˈzɪs.tɪŋ/" },
    { word: "external", meaning: "eksternal", type: "adjective", phonetic: "/ɪkˈstɜː.nəl/" },
    { word: "extraordinary", meaning: "luar biasa", type: "adjective", phonetic: "/ɪkˈstrɔː.dɪn.ər.i/" },
    { word: "financial", meaning: "keuangan", type: "adjective", phonetic: "/faɪˈnæn.ʃəl/" },
    { word: "formal", meaning: "formal", type: "adjective", phonetic: "/ˈfɔː.məl/" },
    { word: "frequent", meaning: "sering", type: "adjective", phonetic: "/ˈfriː.kwənt/" },
    { word: "global", meaning: "global", type: "adjective", phonetic: "/ˈɡloʊ.bəl/" },
    { word: "helpful", meaning: "bermanfaat", type: "adjective", phonetic: "/ˈhelp.fəl/" },
    { word: "immediate", meaning: "segera", type: "adjective", phonetic: "/ɪˈmiː.di.ət/" },
    { word: "independent", meaning: "mandiri", type: "adjective", phonetic: "/ˌɪn.dɪˈpen.dənt/" },
    { word: "individual", meaning: "individu", type: "adjective", phonetic: "/ˌɪn.dɪˈvɪdʒ.u.əl/" },
    { word: "inner", meaning: "bagian dalam", type: "adjective", phonetic: "/ˈɪn.ər/" },
    { word: "intelligent", meaning: "cerdas", type: "adjective", phonetic: "/ɪnˈtel.ɪ.dʒənt/" },
    { word: "internal", meaning: "internal", type: "adjective", phonetic: "/ɪnˈtɜː.nəl/" },
    { word: "logical", meaning: "logis", type: "adjective", phonetic: "/ˈlɒdʒ.ɪ.kəl/" },
    { word: "mental", meaning: "mental", type: "adjective", phonetic: "/ˈmen.təl/" },
    { word: "negative", meaning: "negatif", type: "adjective", phonetic: "/ˈneɡ.ə.tɪv/" },
    { word: "objective", meaning: "objektif", type: "adjective", phonetic: "/əbˈdʒek.tɪv/" },
    { word: "original", meaning: "asli", type: "adjective", phonetic: "/əˈrɪdʒ.ən.əl/" },
    { word: "particular", meaning: "khusus", type: "adjective", phonetic: "/pəˈtɪk.jə.lər/" },
    { word: "personal", meaning: "pribadi", type: "adjective", phonetic: "/ˈpɜː.sən.əl/" },
    { word: "physical", meaning: "fisik", type: "adjective", phonetic: "/ˈfɪz.ɪ.kəl/" },
    { word: "positive", meaning: "positif", type: "adjective", phonetic: "/ˈpɒz.ə.tɪv/" },
    { word: "practical", meaning: "praktis", type: "adjective", phonetic: "/ˈpræk.tɪ.kəl/" },
    { word: "previous", meaning: "sebelumnya", type: "adjective", phonetic: "/ˈpriː.vi.əs/" },
    { word: "professional", meaning: "profesional", type: "adjective", phonetic: "/prəˈfeʃ.ən.əl/" },
    { word: "rare", meaning: "jarang", type: "adjective", phonetic: "/reər/" },
    { word: "realistic", meaning: "realistis", type: "adjective", phonetic: "/ˌriː.əˈlɪs.tɪk/" },
    { word: "recent", meaning: "baru-baru ini", type: "adjective", phonetic: "/ˈriː.sənt/" },
    { word: "relevant", meaning: "relevan", type: "adjective", phonetic: "/ˈrel.ə.vənt/" },
    { word: "remarkable", meaning: "luar biasa", type: "adjective", phonetic: "/rɪˈmɑː.kə.bəl/" },
    { word: "responsible", meaning: "bertanggung jawab", type: "adjective", phonetic: "/rɪˈspɒn.sə.bəl/" },
    { word: "scientific", meaning: "ilmiah", type: "adjective", phonetic: "/ˌsaɪ.ənˈtɪf.ɪk/" },
    { word: "sensitive", meaning: "sensitif", type: "adjective", phonetic: "/ˈsen.sɪ.tɪv/" },
    { word: "significant", meaning: "signifikan", type: "adjective", phonetic: "/sɪɡˈnɪf.ɪ.kənt/" },
    { word: "similar", meaning: "mirip", type: "adjective", phonetic: "/ˈsɪm.ɪ.lər/" },
    { word: "specific", meaning: "spesifik", type: "adjective", phonetic: "/spəˈsɪf.ɪk/" },
    { word: "stable", meaning: "stabil", type: "adjective", phonetic: "/ˈsteɪ.bəl/" },
    { word: "standard", meaning: "standar", type: "adjective", phonetic: "/ˈstæn.dəd/" },
    { word: "strict", meaning: "ketat/disiplin", type: "adjective", phonetic: "/strɪkt/" },
    { word: "successful", meaning: "sukses", type: "adjective", phonetic: "/səkˈses.fəl/" },
    { word: "sufficient", meaning: "cukup", type: "adjective", phonetic: "/səˈfɪʃ.ənt/" },
    { word: "suitable", meaning: "cocok", type: "adjective", phonetic: "/ˈsuː.tə.bəl/" },
    { word: "temporary", meaning: "sementara", type: "adjective", phonetic: "/ˈtem.pə.rer.i/" },
    { word: "traditional", meaning: "tradisional", type: "adjective", phonetic: "/trəˈdɪʃ.ən.əl/" },
    { word: "typical", meaning: "tipikal", type: "adjective", phonetic: "/ˈtɪp.ɪ.kəl/" },
    { word: "unique", meaning: "unik", type: "adjective", phonetic: "/juːˈniːk/" },
    { word: "universal", meaning: "universal", type: "adjective", phonetic: "/ˌjuː.nɪˈvɜː.səl/" },
    { word: "unusual", meaning: "tidak biasa", type: "adjective", phonetic: "/ʌnˈjuː.ʒu.əl/" },
    { word: "valuable", meaning: "berharga", type: "adjective", phonetic: "/ˈvæl.ju.ə.bəl/" },
    { word: "visible", meaning: "terlihat", type: "adjective", phonetic: "/ˈvɪz.ə.bəl/" },
    { word: "willing", meaning: "bersedia", type: "adjective", phonetic: "/ˈwɪl.ɪŋ/" }
];